# -*- coding: utf-8 -*-
# Rewrites of items that were too fine-grained for an oral examination:
# the topic is kept, the question is reframed as "what is the rule / why is it so"
# instead of "compute this value / recall this byte".
ITEMS = [
{
 "id": "appC-natural-encoding-shape",
 "ch": "C", "section": "C.1 General Natural Number Serialization",
 "gpRef": "§C.1", "difficulty": 2, "kind": "concept",
 "tags": ["codec", "encoding", "bijection"],
  "stemZh": "GP §C.1 為一般的自然數給出了一種變長編碼 E(x)。是什麼決定一個值佔幾個位元組？為什麼這個設計對 GP 而言是被逼出來的、而不只是方便？",
  "optionsZh": [
   "第一個位元組裡的前綴宣告了長度，而每個值恰有唯一一種有效編碼；state root 雜湊的是編碼後的狀態，所以一個值有兩種編碼、或一段編碼能被讀成兩個值，都會讓誠實節點對 root 產生分歧",
   "編碼器輸出最少的位元組數，而解碼器靠掃描終止位元組來還原長度；唯一性只是一種慣例，鼓勵但不強制實作遵守，因為 state root 取的是解碼後的值",
   "每個自然數都被填補到固定的八個位元組，好讓結構內的欄位偏移量保持不變；正是這個固定寬度使編碼成為單射，而較短的形式只存在於不做雜湊的 work-package 酬載中",
   "長度由外層結構自己的長度前綴在帶外攜帶，所以 E(x) 本身只是小端序的數字；GP 依靠外層元組讓整體編碼無歧義，而不是依靠 E(x) 本身"
  ],
  "stem": "GP §C.1 gives a variable-length encoding E(x) for a general natural number. What determines how many octets a value takes, and why is that design forced on the GP rather than merely convenient?",
 "options": [
  "A prefix in the first octet announces the length, and each value has exactly one valid encoding; the state root hashes encoded state, so two encodings of one value — or one encoding readable as two values — would let honest nodes disagree on the root",
  "The encoder emits the minimum number of octets and a decoder recovers the length by scanning for a terminator octet; uniqueness is a convention that implementations are encouraged but not required to follow, since the state root is taken over the decoded values",
  "Every natural number is padded to a fixed eight octets so that field offsets inside a structure are constant; the fixed width is what makes the encoding injective, and shorter forms exist only inside work-package payloads where no hashing occurs",
  "The length is carried out-of-band by the enclosing structure's own length prefix, so E(x) itself is just the little-endian digits; the GP relies on the enclosing tuple to make the whole encoding unambiguous rather than on E(x) alone",
 ],
 "answer": 0,
 "explanation": "§C.1 的通用自然數編碼是「前綴決定長度」的變長編碼，值域到 2^64、輸出 1 到 9 個位元組：E(0) = [0]；當 2^(7l) ≤ x < 2^(7(l+1))（l ∈ N_8）時，第一個位元組是 2^8 − 2^(8−l) + ⌊x / 2^(8l)⌋，後面接 E_l(x mod 2^(8l))；x 再大就用 [255] ⌢ E_8(x)。直觀說法：**第一個位元組的高位有幾個連續的 1，後面就跟幾個位元組**，所以小數值只佔一兩個位元組，而讀取端看第一個位元組就知道要再吃幾個，不需要往前掃描或依賴外層資訊。**真正的重點是雙射（bijective）**——附錄 D 的 state root 是對**編碼後的位元組**做 hash，不是對解碼後的值。於是「同一個值有兩種寫法」會讓兩個誠實節點算出不同的 root（共識直接分裂），「同一串位元組能解成兩個值」則讓一份 Merkle 證明可以被挪用到另一個值上。這也是為什麼字典必須先依 key 排序再編碼：正規化（canonicalisation）是編碼規格的一部分，不是實作可自由發揮的細節。**別和 E_l 搞混**：E 是這個變長編碼；E_l（如 E_2、E_4、E_8）是定寬的 little-endian 整數，用在長度、時槽、索引這類「寬度本來就固定」的欄位上，兩者在 GP 裡並存、各有各的場合。",
 "optNotes": [
  "前綴宣告長度 + 唯一編碼，理由正是 state root 對編碼結果取 hash。",
  "掃描終止位元組不是 GP 的做法，且雙射是規格要求而非慣例——state root 取的是編碼後的位元組，不是解碼後的值。",
  "固定八位元組正是 E_n 的做法，不是通用 E；把所有整數補到 8 bytes 會讓狀態與證明肥好幾倍。",
  "外層長度前綴管的是序列有幾個元素，不能取代單一整數自身的長度資訊。",
 ],
 "trap": "被問「為什麼編碼要雙射」時，答案要落在 state root 與證明上，不是「比較整齊」。",
},
{
 "id": "appD-node-discrimination",
  "alsoCh": ["C"],
 "ch": "D", "section": "D.2.1 Trie Node Encoding",
 "gpRef": "§D.2.1", "difficulty": 2, "kind": "concept",
 "tags": ["merklization", "trie", "state-root"],
  "stemZh": "state trie 的節點大小全都一樣。在走訪 trie 時，讀取者如何分辨三種節點？又是什麼決定一個 leaf 存的是值本身、還是只存它的雜湊？",
  "optionsZh": [
   "第一個位元區分 branch 與 leaf、第二個位元區分內嵌值的 leaf 與一般 leaf；至多 32 位元組的值會被內嵌（其長度就放在該位元組剩下的位元裡），更長的則以雜湊取代",
   "節點種類是從抵達它的深度還原的——branch 只出現在最後一層之上——而是否內嵌取決於值能不能塞進扣掉 state key 後剩下的 31 個位元組，所以分界是 31 而不是 32 個位元組",
   "每個節點前有一個位元組的 tag 指名三種之一；只要值比它原本會被換成的那個雜湊還小就會內嵌，這由編碼器逐節點決定並記在該 tag 裡",
   "branch 與 leaf 靠節點後半段是不是一個有效的雜湊原像來區分；值一律以雜湊儲存好讓節點大小固定，而內嵌形式只存在於 service-info 的 leaf 裡"
  ],
  "stem": "State-trie nodes are all the same size. Walking the trie, how does a reader tell the three node kinds apart, and what decides whether a leaf stores the value itself or only its hash?",
 "options": [
  "The first bit separates branch from leaf and the second separates an embedded-value leaf from a regular one; a value of at most 32 octets is embedded (its length lives in the remaining bits of that octet), anything longer is replaced by its hash",
  "The node kind is recovered from the depth at which it was reached — branches only appear above the last level — and embedding is decided by whether the value fits in the 31 octets left over after the state key, so the cut-off is 31 rather than 32 octets",
  "A one-octet tag precedes each node and names one of the three kinds; embedding applies whenever the value is smaller than the hash it would otherwise be replaced by, which the encoder decides per node and records in that tag",
  "Branches and leaves are distinguished by whether the second half of the node is a valid hash preimage; values are always stored by hash so that node size stays fixed, and the embedded form exists only in the service-info leaf",
 ],
 "answer": 0,
 "explanation": "§D.2.1：狀態 trie 的節點**全部固定 512 bit（64 位元組）**，靠開頭兩個 bit 分辨種類——**第一個 bit** 分 branch / leaf，**第二個 bit** 分 embedded-value leaf / regular leaf。**embedded leaf**：首位元組剩下的 6 個 bit 存**值的長度**，接著 31 位元組的 state key，最後 32 位元組直接放值本身（不足補零）。**regular leaf**：那 6 個 bit 歸零，最後 32 位元組改放**值的 hash**。**門檻是 32 位元組，因為那正是尾段的容量**——放得下就直接放，放不下就只留指紋。（也順帶解釋了為什麼長度只需要 6 個 bit：0 到 32 用 6 位表示綽綽有餘。）**固定大小買到什麼**：節點可以像陣列一樣直接定址、**證明大小完全可預測**（深度乘以 64 位元組），不必逐節點量測。**內嵌小值買到什麼**：省掉一次 hash 與一次額外的查詢——狀態裡的餘額、索引、小 metadata 幾乎都在 32 位元組以內，所以這個最佳化命中率很高。**注意 key 是 31 位元組不是 32**：state key 構造函數 C 產生的就是 B_31，剩下的 1 個位元組正好留給判別位與長度——這個「31 + 1 + 32 = 64」的配置不是巧合。",
 "optNotes": [
  "兩個 bit 分三種節點，門檻 32 octet 正好是尾段容量，這是 §D.2.1 的原文結構。",
  "節點種類是自描述的，不靠深度推斷；31 octet 是 state key 的長度，不是值的容量。",
  "沒有額外的 tag 位元組——多一個位元組就破壞 1+31+32 = 64 的固定佈局。",
  "「一律存 hash」會讓每個小值都多一次 hash 與一次查詢，正是 embedded leaf 要避免的。",
 ],
},
{
 "id": "ch07-belt-mmr-shape",
 "ch": "7", "section": "7.4 The Accumulation Output Belt",
 "gpRef": "§7.4; §E.3", "difficulty": 2, "kind": "concept",
 "tags": ["mmr", "beefy", "recent-history"],
  "stemZh": "β_B 是一個 Merkle Mountain Range，每個區塊長出一個 root。描述 append 對這個結構做了什麼，以及 GP 為什麼在這裡選 MMR、而不是每個區塊重建一棵平衡的 Merkle 樹。",
  "optionsZh": [
   "append 把新的 root 放在高度 0，並與任何同高度的既有 peak 向上合併，留下一組 peak，其高度正是計數的二進位位數；這個結構是唯讀附加的，所以每次 append 花 O(log n)，而先前發出的證明仍然有效",
   "append 會重建整個 range，使各 peak 之間的高度始終相差不到一層，藉此讓證明長度一致；舊證明必須在每個區塊後重新發出，這是可接受的，因為 BEEFY 只會證明最新的那個區塊",
   "append 把單一 root 換成「舊 root 與新項目」的雜湊，所以這個 range 其實是一條雜湊鏈；這讓狀態保持很小，並讓驗證者能以常數空間從當前 root 往回走到任何較早的輸出",
   "append 把新 root 插進「區塊 timeslot 模 belt 長度」所指的位置、覆寫原本的內容；因此這條 belt 是環狀緩衝區、舊輸出會自動老化淘汰，鏈上狀態因而有界"
  ],
  "stem": "β_B is a Merkle Mountain Range that grows by one root per block. Describe what the append does to the structure, and why the GP chose an MMR here rather than rebuilding a balanced Merkle tree each block.",
 "options": [
  "Appending places the new root at height 0 and merges it upward with any existing peak of equal height, leaving a set of peaks whose heights are the binary digits of the count; the structure is append-only, so each append costs O(log n) and previously issued proofs remain valid",
  "Appending rebuilds the range so that the peaks are always balanced within one level of each other, which keeps proof length uniform; older proofs must be reissued after each block, which is acceptable because BEEFY only ever proves the most recent block",
  "Appending replaces the single root with the hash of the old root and the new item, so the range is really a hash chain; this keeps the state small and lets a verifier walk backwards from the current root to any earlier output in constant space",
  "Appending inserts the new root at the position given by the block's timeslot modulo the belt length, overwriting whatever was there; the belt is therefore a ring buffer and old outputs age out automatically, which bounds the on-chain state",
 ],
 "answer": 0,
 "explanation": "§E.3 對 MMR 的定義：它是「an append-only cryptographic data structure」，append 與 inclusion proof 都是 O(log N)。型別是 ⟦?H⟧——**一個 peak 序列，索引 i 的 peak 是一棵含 2^i 個項的 Merkle 樹的根**；因為項數不一定是 2^k − 1，某些 peak 會是 ∅ 而不是一個 root。**append 的動作**：新項以高度 0 進來，若該位置已有 peak 就把兩者合併、升到高度 1，再遇到同高度的 peak 就再合併，一路進位上去——完全等同二進位加一。所以 peak 集合永遠對應「目前項數的二進位表示」，非空的 peak 個數就是那個數字的 popcount。**為什麼 JAM 選它而不是每塊重建一棵平衡樹**，兩個性質都關鍵：其一，append 只碰 O(log n) 個節點，而且**從不改寫既有節點**；其二，正因為不改寫，**先前發出去的證明不會失效**。accumulation output 恰好是「持續產出、由鏈外長期驗證」的資料——BEEFY 對它取 super-peak 後簽名，第三方橋接方可能拿著幾個月前的證明回來驗，平衡樹每加一片葉子就要重算整棵樹、舊證明全部作廢，根本不能用。**一個容易忽略的細節**：GP 說 MMR 通常會先被 hash 過再發布，而「hashing them removes the possibility of further appending」——所以要繼續產生證明的那一方必須保留 peak 序列本身，不能只留那個雜湊值。",
 "optNotes": [
  "peak 合併規則與 append-only 帶來的舊證明有效性，正是選 MMR 的兩個理由。",
  "MMR 不重新平衡；而且 BEEFY 的消費者要驗的常常是舊區塊的輸出，不是只驗最新一筆。",
  "退化成 hash chain 的話，證明某一項要走過它之後的所有項，長度是 O(n) 而不是 O(log n)。",
  "環狀緩衝會讓舊輸出被覆蓋、證明永久失效；那是 ω 與 ξ 的做法，不是 belt 的做法。",
 ],
},
{
 "id": "ch11-assurance-signature",
 "ch": "11", "section": "11.2 Assurances",
 "gpRef": "§11.2", "difficulty": 2, "kind": "concept",
 "tags": ["assurance", "availability", "signature"],
  "stemZh": "一份 assurance 帶有一個「每個 core 一位元」的 bitfield 加上一個簽章。實際被簽的是什麼？如果簽章只涵蓋 bitfield，會壞在哪裡？",
  "optionsZh": [
   "簽章涵蓋的是「父 header 雜湊連同編碼後 bitfield」的一個帶域分隔的雜湊；少了父雜湊，同一份簽好的 bitfield 就能被重播進較晚的區塊，使一位 validator 被算成在為它已不再持有的資料背書",
   "簽章只涵蓋 bitfield，而重播是靠鏈上規則防止的——每位 validator 每個區塊至多出現一次；綁定區塊是多餘的，因為該 extrinsic 本來就在被簽的那個區塊裡面",
   "簽章涵蓋每個被設起位元的 core 其 work-report 雜湊，所以背書者是對特定的 report 做出承諾；父 header 雜湊不涉入，因為 report 的壽命比 guarantee 它的那個區塊還長",
   "簽章涵蓋背書者自己的 validator 索引與 bitfield，這正是鏈能歸屬該 assurance 的依據；父雜湊是另外拿去和 header 比對來檢查的，而不是靠被簽進去"
  ],
  "stem": "An assurance carries a bitfield with one bit per core plus a signature. What is actually signed, and what would break if the signature covered only the bitfield?",
 "options": [
  "The signature covers a domain-separated hash of the parent header hash together with the encoded bitfield; without the parent hash the same signed bitfield could be replayed into a later block, letting a validator be counted as assuring data it no longer holds",
  "The signature covers only the bitfield, and replay is prevented by the on-chain rule that each validator may appear at most once per block; binding a block would be redundant because the extrinsic is already inside the block being signed",
  "The signature covers the work-report hashes of every core whose bit is set, so an assurer commits to specific reports; the parent header hash is not involved because reports outlive the block in which they were guaranteed",
  "The signature covers the assurer's own validator index and the bitfield, which is what lets the chain attribute the assurance; the parent hash is checked separately by comparing it against the header rather than by being signed",
 ],
 "answer": 0,
 "explanation": "eq. 11.14 把簽章訊息寫得很死：∀a ∈ E_A，a 的簽章必須是 **X_A ⌢ Blake2b(E(H_P, a_availabilities))**，其中 X_A ≡ `$jam_available` 是 domain separator，H_P 是**父 header 的雜湊**，a_availabilities 是那串每個 core 一位元的 bitfield。驗簽用的公鑰是 κ[a_v]_ed——**prior** active set 裡該 assurer 的 Ed25519 金鑰。**綁 parent hash 的用意是把這份表態鎖在某一個特定的鏈上位置。** 少了它，同一份簽名就是一張可以無限重放的票：別人撿去塞進之後任何一塊，讓一個早就把 shard 丟掉、甚至已經離線的 validator 持續被計入可得性門檻。而那個門檻（2/3 + 1 的超級多數）正是「這份資料還救得回來」的**唯一**保證——它一旦失真，auditor 就可能拿不到重跑 refine 所需的資料，整條稽核鏈跟著失效。**為什麼用 bitfield 而不是逐份報告簽名**：一個 validator 每塊可能同時持有數百個 core 的 shard，逐一簽名會讓簽章數與驗簽成本變成 C 倍（full 設定下 C = 341）。**還有一條配套規則**：某一位只有在對應 core 確實有 availability assignment 時才能被設起來（ρ†[c] ≠ ∅），否則就是在為不存在的工作背書。",
 "optNotes": [
  "綁 parent header hash 是為了防重放，這正是它被納入簽章輸入的理由。",
  "「每塊最多出現一次」擋得住同一塊內的重複，擋不住把舊簽名搬到後面的區塊。",
  "assurance 表態的是「我持有這些 core 的 shard」，不對特定 report hash 簽名——這正是 bitfield 的設計。",
  "validator index 由 extrinsic 欄位攜帶並用來取公鑰驗簽，不是靠簽章內容來歸屬。",
 ],
},
{
 "id": "ch14-oversize-rule",
  "alsoCh": ["11"],
 "ch": "14", "section": "14.4 Work Result Size",
 "gpRef": "§14; eq. 11.x (W_R)", "difficulty": 2, "kind": "concept",
 "tags": ["work-report", "oversize", "limits"],
  "stemZh": "一份 work-package 的各項目接連 refine，而 report 有大小上限 W_R。這個上限是逐項套用、還是套用於整份 report？會越界的項目又會怎麼樣？",
  "optionsZh": [
   "是累計的：每個項目的輸出是拿 authorizer trace 加上已被接受的輸出一起衡量，而第一個會越過 W_R 的項目，其輸出被換成 OVERSIZE 錯誤，後面的項目仍照常 refine",
   "是逐項的：每個輸出各自與 W_R 比較，所以一份 package 只有在單一項目過大時才會失敗；整份 report 是無界的，因為需要由可得性承載的是 bundle 而不是 report",
   "是累計的，但越過上限會使整份 work-report 失效，所以 guarantor 必須丟棄該 package、其所有項目都不會被 report——這正是阻止某個 service 靠灌水輸出把別人擠掉的機制",
   "是累計的，而輸出是被截斷而非替換，截斷長度記在 digest 裡，好讓重跑 refine 的 auditor 能重現出完全相同的位元組"
  ],
  "stem": "A work-package's items refine one after another and the report has a size ceiling W_R. Is the ceiling applied per item or to the report as a whole, and what happens to an item that would cross it?",
 "options": [
  "It is cumulative: each item's output is measured against the authorizer trace plus the outputs already accepted, and the first item that would cross W_R has its output replaced by the OVERSIZE error while later items are still refined normally",
  "It is per item: each output is compared against W_R on its own, so a package can only fail if a single item is oversized; the report as a whole is unbounded because the bundle, not the report, is what availability has to carry",
  "It is cumulative, but crossing the ceiling invalidates the entire work-report, so the guarantors must drop the package and none of its items are reported — this is what stops a service from padding its output to squeeze others out",
  "It is cumulative and the outputs are truncated rather than replaced, with the truncation length recorded in the digest so that an auditor re-running refine can reproduce exactly the same bytes",
 ],
 "answer": 0,
 "explanation": "大小檢查是**累計**的，而且累計的定義很精確。§14 的 countupexports 裡：z = |authtrace| + Σ_{k < j, 且第 k 項的結果 r ∈ B} |r|，也就是 authorizer trace 的長度，加上**排在前面、而且結果確實是 blob** 的那些項的輸出長度；已經出錯的項不計入。判斷式是 |r| + z > W_R，成立就把**這一項**的 result 換成 ⊖ OVERSIZE。W_R = C_maxreportvarsize = 48 · 2^10 = 49,152 位元組，管的是一份 work-report 裡所有不定長 blob 的總量。**兩個關鍵**：其一，被換掉的是該項的 result，**不是整份報告作廢**——後面的 item 照樣 refine，可能還是成功的，而且被換掉那項的 gas 用量 u 與匯出 segment 數仍然保留。其二，**順序有意義**：同一組 item 換個順序，爆掉的可能是不同的那一個，因為 z 是照 j 的順序累加的。**為什麼 OVERSIZE 是錯誤值而不是「無效」**：它屬於 work error set 𝔼 = {∞ OOG, ☇ panic, BADEXPORTS, ⊖ OVERSIZE, BAD, BIG}，是一個會被寫進 work-digest、accumulate 讀得到的**結果**，服務端可以自己處理（例如下次拆小一點再送）。要區分的是另一條規則：若 authorizer trace 自己就超過 W_R（authtrace ∉ B_{:W_R}），那是整份報告的錯誤 E，不是某一項的 OVERSIZE。",
 "optNotes": [
  "累計判斷、第一個越界的項被換成 OVERSIZE、後續照跑，三點都對上 §14 的規則。",
  "若只逐項比對，四個各佔 W_R 八成的 item 就能組出遠超上限的報告，鏈上限制形同虛設。",
  "整份報告作廢的話，一個 item 的失控就能吃掉同包其他服務的工作，OVERSIZE 也就不必列進 𝔼。",
  "GP 沒有截斷語意；截斷會讓 refine 的輸出不再是純函數的完整結果，auditor 重跑的比對基準也會變模糊。",
 ],
},
{
 "id": "appA-fault-address-rule",
 "ch": "A", "section": "A.4 Memory & Page Faults",
 "gpRef": "eq. A.9", "difficulty": 2, "kind": "concept",
 "tags": ["pvm", "page-fault", "memory"],
  "stemZh": "一次多位元組的 store 跨越了兩個 page：第一個可寫、第二個未配置。PVM 會回報什麼？回報的位址為什麼要那樣定義？",
  "optionsZh": [
   "一個 page fault，帶著「此次存取所觸及、最低的不可存取位元組」其 page 對齊後的位址；對齊到 page 正是讓這個值成為 host 能據以行動的東西——它恰好就是 host 在恢復程式前必須映射的那個 page",
   "一個 page fault，帶著第一個不可存取位元組的精確位址，好讓 host 確知存取停在哪裡；host 被預期要自行對齊該值再映射，因為對齊是 host 的事、不屬於機器語意",
   "一個 panic，因為跨越 page 邊界進入未配置記憶體的存取按定義就是畸形的；page fault 保留給完全落在單一個未映射 page 之內、因而能靠映射一個 page 就滿足的存取",
   "一個 page fault，帶著「含有此次存取起點」那個 page 的基底位址，好讓整次存取能從一個已知已映射的位置重試；機器會先寫入可存取的前綴，再從 fault 位址繼續"
  ],
  "stem": "A multi-octet store straddles two pages: the first is writable, the second is not allocated. What does the PVM report, and why is the reported address defined the way it is?",
 "options": [
  "A page fault carrying the page-aligned address of the lowest inaccessible octet touched by the access; aligning to the page is what makes the value something the host can act on — it is exactly the page the host must map before the program is resumed",
  "A page fault carrying the exact address of the first inaccessible octet, so the host learns precisely where the access stopped; the host is expected to align the value itself before mapping, since alignment is a host concern rather than part of the machine's semantics",
  "A panic, because an access that crosses a page boundary into unallocated memory is by definition malformed; page faults are reserved for accesses that lie wholly inside a single unmapped page and can therefore be satisfied by mapping one page",
  "A page fault carrying the base address of the page containing the start of the access, so that the whole access can be retried from a known-mapped position; the machine writes the accessible prefix first and resumes from the fault address",
 ],
 "answer": 0,
 "explanation": "eq. A.9 把 page fault 的參數定義成「**被觸及的位址中最低的那個不可存取位址，向下對齊到 Z_P = 2^12 的頁邊界**」。**為什麼回報頁而不是精確位址**：host 唯一能做的補救就是把那一頁映射進來再續跑，給它一個頁對齊的位址剛好可以直接拿去用，不必自己再算一次對齊。**為什麼取「最低的那個」**：跨頁存取可能碰到不只一個不可存取的頁，從最低的開始補才能保證進度單調前進，不會來回震盪。**page fault 是可回復的退出理由，不是 panic**——這一點常被誤解。理由很實際：refine 要按需載入 import segment、accumulate 要按需取 storage；如果一開始就得把所有**可能**用到的資料全塞進記憶體，work-package 會大到不可行。按需分頁讓「宣告可能用到很多、實際只碰一小部分」變成可行的模式。**還有一個確定性要求**：跨頁存取**不會先寫入可存取的那一半**——整個存取要嘛完整發生、要嘛完全不發生。若允許部分寫入，auditor 重跑時記憶體狀態就可能與原執行不同，稽核的可比對性就沒了。",
 "optNotes": [
  "最低不可存取位址、向下對齊到頁邊界，正是 eq. A.9 的定義，理由也在「host 要映射的是一整頁」。",
  "精確位址對 host 沒有多餘用處，而 GP 明確把對齊寫進了公式，不是留給 host 做。",
  "跨頁存取不是 malformed；fault 本來就要處理「一部分可存取」的情形，否則按需載入無法運作。",
  "回報存取起點所在的頁會指到一個**已經映射好**的頁，host 照著做等於沒補救，而且部分寫入會破壞可重現性。",
 ],
},
{
 "id": "appA-jump-semantics",
 "ch": "A", "section": "A.3 Basic Blocks & Control Transfer",
 "gpRef": "§A.3; §A.5", "difficulty": 2, "kind": "concept",
 "tags": ["pvm", "control-flow", "gas"],
  "stemZh": "PVM 同時有靜態解析的跳躍與由暫存器算出的間接跳躍。間接跳躍的目標必須額外滿足哪些條件？如果把這些條件拿掉，gas 模型會壞在哪裡？",
  "optionsZh": [
   "間接跳躍的目標必須對齊、非零、位於 jump table 之中，且落在某個 basic block 的起點；少了「落在 block 起點」這項要求，程式就能從第一條指令以下進入一個 block 並執行它，而該 block 的 gas 從未被計費",
   "間接跳躍的目標只需落在 code blob 之內並且對齊；不要求 block 起點，因為機器會從程式計數器重新導出所在的 block 並在進入時計費，所以不論如何 gas 計帳都不受影響",
   "間接跳躍的目標必須是程式符號表所記載的某個函數起點，而那正是 jump table 所存的東西；gas 模型不受影響，因為間接跳躍以立即運算元攜帶自己的 gas 成本",
   "間接跳躍的目標只需是 page 大小的倍數，好讓一次跳躍永遠不會跨 page；gas 是按退休的指令數而不是按 block 計費，所以控制流落在哪裡對計帳毫無影響"
  ],
  "stem": "The PVM has both statically-resolved jumps and indirect jumps computed from a register. What extra conditions must an indirect target satisfy, and what would break in the gas model if they were dropped?",
 "options": [
  "An indirect target must be aligned, non-zero, inside the jump table and land on a basic-block start; without the block-start requirement a program could enter a block below its first instruction and execute it without the block's gas ever being charged",
  "An indirect target must merely lie inside the code blob and be aligned; block starts are not required because the machine re-derives the enclosing block from the program counter and charges that block on entry, so gas accounting is unaffected either way",
  "An indirect target must be the start of a function as recorded in the program's symbol table, which is what the jump table holds; the gas model is unaffected because indirect jumps carry their own gas cost as an immediate operand",
  "An indirect target only has to be a multiple of the page size, so that a jump can never straddle a page; gas is charged per instruction retired rather than per block, so where control lands has no bearing on the accounting",
 ],
 "answer": 0,
 "explanation": "**靜態跳躍**（jump、load_imm_jump）帶的是有號的 PC 相對位移，組譯期就能解析，沒有額外條件。**間接跳躍**（jump_ind、load_imm_jump_ind）的目標由暫存器算出來，執行前無法預知，所以 GP 加了四個條件：對齊 Z_A（= 2）、**非零**、落在 jump table 範圍內（a ≤ |j| · Z_A）、而且 j[a/Z_A − 1] 必須是一個 **basic block 的起點**。**最後一條與 0.8.0 的 gas 模型直接相扣**：gas 是在「進入 basic block」時**整塊預先扣掉**的，金額由該 block 的指令靜態加總而來。如果可以從 block 的中間切進去，那段指令就會在**沒有被計價的情況下執行**——而且可以反覆這樣做，等於無限的免費計算，整個計價模型直接崩潰。**非零那條**是為了讓 0 保留給「無效目標」的語意（配合 ζ 補零後 opcode 0 = trap）。**對齊那條的理由 GP 自己說了**：是 LLVM 相容性——LLVM 產碼時假設動態跳躍目標有一定的對齊，順著它可以少一層轉換。**口試角度**：這題真正在問的是「為什麼間接跳躍需要比靜態跳躍更多的檢查」，答案是**靜態的可以在編譯期驗證，動態的只能在執行期驗證，而計價的完整性依賴這個驗證**。",
 "optNotes": [
  "四個條件與「block 起點保證 gas 一定被收過」的關聯，正是這題要考的設計連動。",
  "PVM 不會在跳躍後回頭補收 block 的 gas；預扣發生在進入 block 的那一刻，所以落點必須受限。",
  "jump table 存的是合法跳躍目標，不是符號表；指令也沒有攜帶 gas 立即數。",
  "頁大小與控制流無關，而 0.8.0 早已不是每指令計價——這是 0.7.2 的模型。",
 ],
 "trap": "被問「為什麼間接跳躍要限制目標」時，先講 gas，再講 LLVM 對齊，順序反過來會顯得只背了條文。",
},
{
 "id": "appB-gas-model",
 "ch": "B", "section": "B.1 Host Call Gas",
 "gpRef": "§B（PR #517）", "difficulty": 2, "kind": "delta",
 "tags": ["host-call", "gas", "delta-0.8.0"],
  "stemZh": "GP 0.8.0 重做了 host call 的計費方式。描述新收費的形狀，以及當一個 service 呼叫某個在它這次 invocation 中不可用的索引時會發生什麼。",
  "optionsZh": [
   "每個呼叫有一個基本成本，並在它搬移資料時再加上一項與所觸及 KiB 數成正比的費用；未知或不可用的索引會先被收取一個預設成本，所以剩餘 gas 不足的呼叫會以 out-of-gas 退出、而不是回傳錯誤碼",
   "每個呼叫不論搬多少資料都收同樣的固定金額，這正是讓 basic block 的成本能靜態算出的原因；未知索引是免費的、單純回傳 WHAT，因為對什麼都沒做的呼叫收費並不公平",
   "成本是在呼叫之後、依 host 實際消耗的 gas 計算的，所以搬愈多資料的呼叫自然愈貴；未知索引回傳 WHAT，而機器不收任何費用、計數器原封不動",
   "成本由 service 在其 metadata 中宣告、並於註冊時驗證，這讓 service 能為自己的最壞情況設限；未知索引會以 panic 中止整個 accumulation，好讓錯誤在開發期間高聲浮現"
  ],
  "stem": "GP 0.8.0 reworked how a host call is charged. Describe the shape of the new charge and what happens when a service invokes an index that is not available in its invocation.",
 "options": [
  "Each call has a base cost plus, where it moves data, a term proportional to the number of KiB touched; an index that is unknown or unavailable is charged a default cost first, so a call with too little gas left exits out-of-gas rather than returning an error code",
  "Each call costs the same flat amount regardless of the data it moves, which is what keeps a basic block's cost statically computable; an unknown index is free and simply returns WHAT, since charging for a call that did nothing would be unfair",
  "The cost is computed after the call from the gas the host actually consumed, so a call that moves more data naturally costs more; an unknown index returns WHAT and the machine charges nothing, leaving the counter untouched",
  "Costs are declared by the service in its metadata and validated at registration, which lets a service bound its own worst case; an unknown index aborts the whole accumulation with a panic so that mistakes surface loudly during development",
 ],
 "answer": 0,
 "explanation": "0.8.0（PR #517）把 host call 的計價改成「**基本成本 + 資料量項**」：每個呼叫有自己的 base cost，會搬資料的再加上按 KiB 計的線性部分（`grow_heap` 就是典型：常數項加上與新增頁數成正比的項）。**面試價值在它與兩件事的互動。****其一，先扣後做。** 不認得的、或在當前 invocation 不可用的 host call index，**會先被收一筆預設成本**，然後才判定它不可用。所以餘額不足時的結果是 **∞（out-of-gas，整個 invocation 收掉並回到最近的 checkpoint）**，而不是乖乖回一個 WHAT 錯誤碼。這是實作很容易寫反的地方——直覺會先檢查合法性再扣款，但規格是反過來的。**為什麼要這樣**：否則呼叫不存在的 index 就變成一個零成本的探測操作，可以用來免費地試探環境。**其二，兩層計價互相獨立。** 附錄 A 的 basic-block 預扣管的是指令，host call 的成本**不會**被算進 block 的預扣裡——這正是為什麼動態成本的操作必須做成 host call 而不是指令（0.8.0 移除 sbrk 就是這個原因）。",
 "optNotes": [
  "base + 每 KiB、以及不明 index 先扣預設成本導致可能 OOG，兩點都是 0.8.0 的規定。",
  "0.8.0 已經不是齊頭式定價；而且 block 的靜態成本與 host call 的成本本來就分屬兩層。",
  "事後依實際消耗計價無法跨實作重現，等於放棄確定性——GP 的成本一律是規格寫死的。",
  "服務不能自訂 host call 價目；讓 service 宣告成本等於讓它自己決定攻擊成本。",
 ],
},
{
 "id": "appB-grow-heap-semantics",
 "ch": "B", "section": "B.2 grow_heap",
 "gpRef": "§B（PR #508 / #517）", "difficulty": 2, "kind": "delta",
 "tags": ["host-call", "memory", "delta-0.8.0"],
  "stemZh": "GP 0.8.0 移除了 sbrk 指令，改以 grow_heap 這個 host call 提供堆積成長。呼叫者要傳什麼？在 0.8.0 的 gas 模型下，為什麼 host call 才是這個操作的正確歸屬？",
  "optionsZh": [
   "呼叫者指名它想要的堆積終點，並依新變為可寫的 page 數按比例計費；一條成本取決於其運算元的指令會破壞「basic block 的價格能在該 block 執行前靜態算出」這個保證",
   "呼叫者傳入要增加的位元組數並被收取固定金額；它被移出指令集純粹是為了編碼空間，因為該 opcode 得留給 0.8.0 新引入的某條無引數指令",
   "呼叫者傳入 page 數量而該呼叫免費，因為記憶體在程式初始化時就已保留；把它做成 host call 只是為了讓 host 能在機器被巢狀於某個內層 PVM 時拒絕成長",
   "呼叫者傳入想要的終點 page，而成本事後才依 host 實際的配置成本結算，這正是它不能是指令的原因——指令必須在執行前就知道成本，而 host call 是回傳時才計費"
  ],
  "stem": "GP 0.8.0 removes the sbrk instruction and provides heap growth as the grow_heap host call instead. What does the caller pass, and why is a host call the right home for this operation under the 0.8.0 gas model?",
 "options": [
  "The caller names the heap end it wants and is charged in proportion to the pages newly made writable; an instruction whose cost depends on its operand would break the promise that a basic block's price can be computed statically before the block runs",
  "The caller passes the number of octets to add and is charged a flat amount; it was moved out of the instruction set purely for encoding space, since the opcode was needed for one of the new no-argument instructions introduced in 0.8.0",
  "The caller passes a page count and the call is free, because the memory was already reserved when the program was initialized; making it a host call simply lets the host refuse growth when the machine is nested inside an inner PVM",
  "The caller passes the desired end page and the cost is settled afterwards from the host's actual allocation cost, which is why it cannot be an instruction — instructions must have their cost known before they execute, but host calls are charged on return",
 ],
 "answer": 0,
 "explanation": "grow_heap 是 host call 編號 1（GP 寫作 Ω_♊），三種 invocation——refine、accumulate、on-transfer——都可以呼叫。呼叫者在 φ_7 放「想要的堆結尾」，計價是常數項加線性項：g = C_gas♊const + (φ_7 − h) · C_gas♊linear，h 是目前的堆結尾；若 φ_7 ≤ h（沒有實際成長）或 φ_7 > b（超過上界），就只扣常數項、什麼也不做。**為什麼要從指令搬成 host call**，理由跟 0.8.0 的 gas 模型直接相扣：附錄 A 改成**以 basic block 為單位、進入時預先扣款**，而「預扣」的前提是這個 block 的價格能在**執行之前靜態算出**——把 block 裡每條指令的固定成本加總即可。一條成本取決於運算元的指令會直接打破這個前提：你不執行就不知道這次 sbrk 要長幾頁，也就算不出預扣金額。搬成 host call 之後，分工變得乾淨：**指令層一律靜態可計價，動態成本統一走 host call 那條「先算價、再扣、再做」的路徑**。這也是 0.8.0 移除 sbrk 的原因（PR #508 引入 block-level gas、#517 收尾），不是因為 sbrk 本身有錯，而是它與新的計價模型不相容。相關名詞：ϱ 是 gas 計數器、ϖ 是 basic block（以 terminator 指令切分，正是計價與跳躍目標的單位）。",
 "optNotes": [
  "指定結尾頁、按新增頁數計費，理由落在「block 價格必須靜態可算」，這正是 0.8.0 的連動。",
  "動機不是編碼空間；把它留在指令集裡會直接破壞 block-level 預扣的前提。",
  "記憶體不是初始化時就全部保留，否則 grow_heap 沒有存在意義，也不會需要計費。",
  "host call 同樣是先扣後做，不是事後結算——事後結算無法保證跨實作一致。",
 ],
},
{
 "id": "appB-fetch-purpose",
 "ch": "B", "section": "B.2 fetch",
 "gpRef": "§B", "difficulty": 2, "kind": "concept",
 "tags": ["host-call", "refine", "design"],
  "stemZh": "fetch 是單一個 host call、在三種 invocation 中都可用，其第一個引數選擇要讀哪一份資料。GP 為什麼把這麼多資料來源摺進同一個呼叫，而不是各給一個索引？",
  "optionsZh": [
   "因為 host call 的編號是每個已部署 service 所編譯依循的 ABI 的一部分：用一個選擇子引數就能新增資料來源而不必重新編號，而每個來源各給一個新索引，最終會逼既有 service 重新建置",
   "因為每種 invocation 暴露的來源子集不同，而單一個呼叫是唯一能表達這件事的方式——若用分開的索引，機器就無法分辨哪些在 refine 中合法、哪些在 accumulate 中合法",
   "因為這些來源共用同一個 gas 價格，而 GP 是按 host-call 索引計費；把它們摺在一起才使得讀取協定常數的價格與讀取 work-package 匯入的價格完全相同",
   "因為選擇子讓該呼叫的暫存器簽章維持在 host call 可用的四個引數暫存器之內，而分開的索引做不到這點，因為每個來源都需要自己的偏移量與長度配對"
  ],
  "stem": "fetch is a single host call, available in all three invocations, whose first argument selects which piece of data to read. Why did the GP fold this many data sources into one call instead of giving each its own index?",
 "options": [
  "Because the host-call numbering is part of the ABI every deployed service compiles against: a selector argument lets new data sources be added without renumbering anything, while a new index per source would eventually force existing services to be rebuilt",
  "Because each invocation exposes a different subset of the sources, and a single call is the only way to express that — with separate indices the machine could not tell which ones are legal in refine as opposed to accumulate",
  "Because the sources share one gas price, and the GP charges per host-call index; folding them together is what keeps the price of reading the protocol constants identical to the price of reading a work-package's imports",
  "Because a selector keeps the call's register signature within the four argument registers available to host calls, which separate indices could not do since each source needs its own offset and length pair",
 ],
 "answer": 0,
 "explanation": "`fetch` 用 φ_10 當 **selector** 選擇要讀哪一種資料——協定常數、entropy、authorizer trace、extrinsic 與 import 的內容、work-package 的各個部分等等。三種 invocation（refine、accumulate、on-transfer）都能呼叫它，只是各自可取的來源不同。**收成一個呼叫的理由是 ABI 穩定性。** host call 的**編號是介面的一部分**——所有已部署的 service 在編譯時就把 `ecalli 3` 這種數字寫死在程式碼裡了。每多一種資料就配一個新編號，編號空間遲早要重新整理，而**重新編號會讓既有的 service 全部失效**，因為它們呼叫的還是舊數字。**這不是假想的風險**：0.8.0 移除 sbrk 導致後面的 opcode 位移，就是同一類痛的實例（雖然那是指令不是 host call）。**selector 則是資料層的參數**：新增一種來源只要多定義一個 selector 值，既有 service 完全不受影響，因為它們傳的還是自己那個值。**通則**：把「會持續增加的維度」放進參數而不是放進介面編號，這是任何長期演化的 ABI 都會做的取捨——代價是呼叫端要多傳一個參數、而且單一呼叫的語意變得比較複雜。",
 "optNotes": [
  "ABI 穩定、加來源不必動編號，正是把多來源收進單一 fetch 的理由。",
  "「哪些來源在哪個 invocation 可用」用個別編號一樣表達得出來——那只是 dispatch 表的事。",
  "同一個 fetch 的不同來源本來就可能因搬運資料量而價格不同，不是齊頭定價。",
  "暫存器數量不是限制：每個來源本來就只需要 selector 加上輸出緩衝的位址與長度。",
 ],
},
{
 "id": "appC-digest-error-encoding",
 "ch": "C", "section": "C.x Work Digest",
 "gpRef": "§C；eq. 11.7（𝔼）", "difficulty": 2, "kind": "concept",
 "tags": ["codec", "work-digest", "errors"],
  "stemZh": "一份 work digest 的 result 欄位存的不是 refine 的輸出、就是錯誤集合 𝔼 的某個成員。這種二擇一是怎麼編碼的？GP 為什麼把 refine 失敗當成值放上鏈，而不是直接拒絕該 report？",
  "optionsZh": [
   "成功是一個判別位元組後接帶長度前綴的 blob，而每種錯誤各是一個相異的單一位元組；把失敗保留為一般的值，讓 accumulate 能確切看到某項目是怎麼失敗的，也讓一個項目失敗不會使 package 中其他項目失效",
   "成功與失敗共用同樣的形狀——帶長度前綴的 blob，失敗時為空——原因另外由 report 的 authorizer trace 攜帶；這讓 digest 保持定寬，而 erasure 編碼器仰賴這一點",
   "錯誤被編碼成任何成功的 refine 都產不出的保留 blob 值，所以不需要判別子；含有錯誤的 report 仍然有效但會被 accumulate 略過，這也是為什麼那些錯誤變體不需要鏈上意義",
   "任一項目失敗就會讓整份 work-report 無效，所以這個編碼根本沒有錯誤的情形；𝔼 集合的存在只是為了替 guarantor 在決定是否簽署 report 前於鏈下檢查的那些條件命名"
  ],
  "stem": "A work digest's result field holds either the refine output or a member of the error set 𝔼. How is that alternative encoded, and why does the GP put refine failures on-chain as values rather than rejecting the report?",
 "options": [
  "Success is a discriminant octet followed by the length-prefixed blob, and each error is a single distinct octet; keeping failures as ordinary values lets accumulate see exactly how an item failed, and lets one item fail without invalidating the others in the package",
  "Success and failure share the same shape — a length-prefixed blob, empty in the failure case — with the reason carried separately in the report's authorizer trace; this keeps the digest fixed-width, which the erasure coder relies on",
  "Errors are encoded as reserved blob values that no successful refine can produce, so no discriminant is needed; a report containing any error is still valid but is skipped by accumulate, which is why the error variants need no on-chain meaning",
  "A failing item makes the whole work-report invalid, so the encoding has no error case at all; the 𝔼 set exists only to name the conditions guarantors check off-chain before deciding whether to sign the report",
 ],
 "answer": 0,
 "explanation": "附錄 C 的 E_result 用一個判別位元組區分成功與失敗，六種錯誤各佔一個值：**成功 = (0, var(blob))**，判別值 0 之後接長度前綴的輸出；失敗則是**單一個位元組**——1 = ∞ out-of-gas、2 = ☇ panic、3 = BADEXPORTS、4 = ⊖ OVERSIZE、5 = BAD、6 = BIG，正好對應 eq. 11.7 的 work error set 𝔼 = {∞, ☇, BADEXPORTS, ⊖, BAD, BIG}。（成功要帶長度、失敗不必，所以失敗的編碼比成功還短。）**把失敗當「值」而不是當「報告無效」是刻意的設計，三個理由**：其一，**accumulate 讀得到失敗原因**——服務可以自己決定要重試、退款還是只記一筆帳，這是把控制權交還給服務端。其二，**同一個 work-package 裡其他 item 不受牽連**；否則一個服務的失控（無窮迴圈、輸出爆量）就能吃掉同一包裡所有人的工作，那會變成一個廉價的攻擊面。其三，**失敗也必須可稽核**——auditor 重跑 refine 時比對的是「同一份輸入是否得到同樣的結果」，而「同樣的結果」包含「同樣地失敗」；若失敗不上鏈，就沒有可比對的對象，一個惡意 guarantor 就能把成功的執行謊報成失敗而不被抓到。",
 "optNotes": [
  "判別位元組 + 單位元組錯誤碼，以及「失敗是值」帶來的三個好處，正是 GP 的設計。",
  "空 blob 無法區分「成功但輸出為空」與「失敗」，而 digest 本來就不是固定寬度。",
  "保留值的做法會讓錯誤與合法輸出混淆；而且 accumulate 確實看得到錯誤，不是跳過。",
  "單一 item 失敗不會讓整份報告無效——OVERSIZE 之所以列在 𝔼 裡就是因為它是可記錄的結果。",
 ],
},
{
 "id": "ch06-fallback-purpose",
 "ch": "6", "section": "6.5 The Slot Key Sequence",
 "gpRef": "eq. 6.25, 6.27 (F)", "difficulty": 2, "kind": "concept",
 "tags": ["safrole", "fallback", "anonymity"],
  "stemZh": "當抵達的 ticket 太少時，γ′_S 會退回到一個由熵與啟用 validator 集合導出的金鑰序列。每個 slot 的出塊者是怎麼選出來的？在 fallback 生效期間，這條鏈放棄了什麼性質？",
  "optionsZh": [
   "每個 slot 的出塊者是把熵與 slot 索引一起雜湊、再對集合大小取模而選出的；整個 epoch 的排程因此可以事先被公開算出，所以 ring VRF ticket 所買到的匿名性在那個 epoch 就沒了",
   "每個 slot 的出塊者是索引等於「slot 編號模集合大小」的那位 validator，所以排程就是單純的輪替；除了公平性之外沒有損失，因為輪替會讓某些 validator 拿到略多的 slot",
   "出塊者是從前一個 epoch 的 ticket 累加器中抽出、重用那些未被消耗的最新 ticket；匿名性得以保留，因為那些 ticket 仍是 ring-VRF 證明，但活性會受損，因為這個池最終會用完",
   "fallback 把每個 slot 都指派給整個 validator 集合、並接受第一個抵達的有效 seal；匿名性不受影響，因為根本沒有排程，代價是偶爾會出現同高度的競爭區塊"
  ],
  "stem": "When too few tickets arrive, γ′_S falls back to a key sequence derived from entropy and the active validator set. How is each slot's author chosen, and what property does the chain give up while the fallback is in force?",
 "options": [
  "Each slot's author is picked by hashing the entropy together with the slot index and reducing the result modulo the set size; the whole epoch's schedule becomes publicly computable in advance, so the anonymity that ring VRF tickets buy is lost for that epoch",
  "Each slot's author is the validator whose index equals the slot number modulo the set size, so the schedule is a plain round robin; nothing is lost beyond fairness, since a round robin gives some validators marginally more slots than others",
  "Authors are drawn from the previous epoch's ticket accumulator, reusing the newest tickets that were not consumed; anonymity is preserved because those tickets are still ring-VRF proofs, but liveness suffers because the pool eventually empties",
  "The fallback assigns every slot to the validator set collectively and accepts the first valid seal to arrive; anonymity is unaffected because no schedule exists, at the cost of occasional competing blocks at the same height",
 ],
 "answer": 0,
 "explanation": "eq. 6.27 把 F 定義得很具體：F(r, k) = [ k[decode_4(Blake2b(r ⌢ E_4(i))[…4])]^⟲ _bs | i ∈ N_E ]。逐步拆：對 epoch 內的每個 slot 索引 i，把 entropy r 接上 i 的 4 位元組編碼一起 Blake2b、取雜湊的**前 4 個位元組**解成整數，用它**對 validator 數取模**（`^⟲` 就是 §3.7 的模數下標記號）選出一位驗證者，再取他的 Bandersnatch 公鑰。r 用的是 η′_2、k 用的是 κ′，兩者都是 posterior。**代價很具體**：這條式子的輸入在 epoch 一開始就全部公開，任何人都能把**整個 epoch 的出塊表**算出來。這正是 ring VRF ticket 花大力氣買來的匿名性——§6 開宗明義說「the identity of the key-holder of any future timeslot will have a very high degree of anonymity」——在 fallback 生效期間完全消失。後果不是理論性的：知道誰在哪個 slot 出塊，針對性 DoS 與事前賄賂都重新變得可行。**GP 仍然這樣設計，是因為活性優先於匿名性**：寧可退化成公開的輪值表，也不要因為票不夠就停鏈。Y = 500 的投票截止線正是為了讓票源有整整 500 個時槽可以累積，盡量不走到這條路上。",
 "optNotes": [
  "hash(entropy ⌢ slot index) 取模選人、以及匿名性全失，兩者是 eq. 6.26 與其代價。",
  "純輪流會讓出塊順序與 validator 索引綁死，任何人都能長期預測，且無法隨 entropy 變動。",
  "fallback 的前提就是票不夠，沒有可重用的票；重用舊票也會讓同一張票決定兩個 epoch。",
  "無排程、先到先得等於放棄單一出塊者，會讓每個 slot 都可能分叉，與 Safrole 的目的相反。",
 ],
 "trap": "「票不夠會怎樣」要答到「出塊表變成公開可算」，只說「用公鑰輪流」等於沒答到重點。",
},
]