# -*- coding: utf-8 -*-
# Rewrites of items that were too fine-grained for an oral examination:
# the topic is kept, the question is reframed as "what is the rule / why is it so"
# instead of "compute this value / recall this byte".
ITEMS = [
{
 "id": "appC-natural-encoding-shape",
 "ch": "C", "section": "C.1 General Natural Number Serialization",
 "gpRef": "§C.1", "difficulty": 2, "kind": "concept",
 "tags": ["codec", "encoding", "bijection"],
 "stem": "GP §C.1 gives a variable-length encoding E(x) for a general natural number. What determines how many octets a value takes, and why is that design forced on the GP rather than merely convenient?",
 "options": [
  "A prefix in the first octet announces the length, and each value has exactly one valid encoding; the state root hashes encoded state, so two encodings of one value — or one encoding readable as two values — would let honest nodes disagree on the root",
  "The encoder emits the minimum number of octets and a decoder recovers the length by scanning for a terminator octet; uniqueness is a convention that implementations are encouraged but not required to follow, since the state root is taken over the decoded values",
  "Every natural number is padded to a fixed eight octets so that field offsets inside a structure are constant; the fixed width is what makes the encoding injective, and shorter forms exist only inside work-package payloads where no hashing occurs",
  "The length is carried out-of-band by the enclosing structure's own length prefix, so E(x) itself is just the little-endian digits; the GP relies on the enclosing tuple to make the whole encoding unambiguous rather than on E(x) alone",
 ],
 "answer": 0,
 "explanation": "§C.1 的通用自然數編碼是「前綴決定長度」的變長編碼：第一個位元組的高位樣式宣告後面還有幾個位元組，小數值因此只佔一兩個位元組。真正的重點是**雙射**——附錄 D 的 state root 是對編碼後的位元組做 hash，所以「同一個值有兩種寫法」會讓兩個誠實節點算出不同的 root，「同一串位元組能解成兩個值」則讓證明可以被挪用。這也是為什麼字典必須先依 key 排序再編碼：正規化是編碼規格的一部分，不是實作細節。",
 "optNotes": [
  "前綴宣告長度 + 唯一編碼，理由正是 state root 對編碼結果取 hash。",
  "掃描終止位元組不是 GP 的做法，且雙射是規格要求而非慣例——state root 取的是編碼後的位元組，不是解碼後的值。",
  "固定八位元組正是 E_n 的做法，不是通用 E；把所有整數補到 8 bytes 會讓狀態與證明肥好幾倍。",
  "外層長度前綴管的是序列有幾個元素，不能取代單一整數自身的長度資訊。",
 ],
 "trap": "被問「為什麼編碼要雙射」時，答案要落在 state root 與證明上，不是「比較整齊」。",
},
{
 "id": "appD-node-discrimination",
 "ch": "D", "section": "D.2.1 Trie Node Encoding",
 "gpRef": "§D.2.1", "difficulty": 2, "kind": "concept",
 "tags": ["merklization", "trie", "state-root"],
 "stem": "State-trie nodes are all the same size. Walking the trie, how does a reader tell the three node kinds apart, and what decides whether a leaf stores the value itself or only its hash?",
 "options": [
  "The first bit separates branch from leaf and the second separates an embedded-value leaf from a regular one; a value of at most 32 octets is embedded (its length lives in the remaining bits of that octet), anything longer is replaced by its hash",
  "The node kind is recovered from the depth at which it was reached — branches only appear above the last level — and embedding is decided by whether the value fits in the 31 octets left over after the state key, so the cut-off is 31 rather than 32 octets",
  "A one-octet tag precedes each node and names one of the three kinds; embedding applies whenever the value is smaller than the hash it would otherwise be replaced by, which the encoder decides per node and records in that tag",
  "Branches and leaves are distinguished by whether the second half of the node is a valid hash preimage; values are always stored by hash so that node size stays fixed, and the embedded form exists only in the service-info leaf",
 ],
 "answer": 0,
 "explanation": "§D.2.1：節點固定 512 bit（64 octet），第一個 bit 分 branch / leaf，第二個 bit 分 embedded-value leaf / regular leaf。embedded 的情況下，首位元組剩下的 6 個 bit 存值的長度，接著 31 octet 的 state key，最後 32 octet 放值本身（不足補零）；regular 的情況下那 6 個 bit 歸零，最後 32 octet 改放值的 hash。門檻是 32 octet，因為那正是尾段的容量。固定大小讓節點可以直接以陣列存取、證明大小完全可預測，而內嵌小值省掉一次 hash 與一次額外查詢——狀態裡的餘額、索引、小 metadata 幾乎都落在這一類。",
 "optNotes": [
  "兩個 bit 分三種節點，門檻 32 octet 正好是尾段容量，這是 §D.2.1 的原文結構。",
  "節點種類是自描述的，不靠深度推斷；31 octet 是 state key 的長度，不是值的容量。",
  "沒有額外的 tag 位元組——多一個位元組就破壞 1+31+32 = 64 的固定佈局。",
  "「一律存 hash」會讓每個小值都多一次 hash 與一次查詢，正是 embedded leaf 要避免的。",
 ],
},
{
 "id": "ch07-belt-mmr-shape",
 "ch": "7", "section": "7.4 The Accumulation Output Belt",
 "gpRef": "§7.4; §E.3", "difficulty": 2, "kind": "concept",
 "tags": ["mmr", "beefy", "recent-history"],
 "stem": "β_B is a Merkle Mountain Range that grows by one root per block. Describe what the append does to the structure, and why the GP chose an MMR here rather than rebuilding a balanced Merkle tree each block.",
 "options": [
  "Appending places the new root at height 0 and merges it upward with any existing peak of equal height, leaving a set of peaks whose heights are the binary digits of the count; the structure is append-only, so each append costs O(log n) and previously issued proofs remain valid",
  "Appending rebuilds the range so that the peaks are always balanced within one level of each other, which keeps proof length uniform; older proofs must be reissued after each block, which is acceptable because BEEFY only ever proves the most recent block",
  "Appending replaces the single root with the hash of the old root and the new item, so the range is really a hash chain; this keeps the state small and lets a verifier walk backwards from the current root to any earlier output in constant space",
  "Appending inserts the new root at the position given by the block's timeslot modulo the belt length, overwriting whatever was there; the belt is therefore a ring buffer and old outputs age out automatically, which bounds the on-chain state",
 ],
 "answer": 0,
 "explanation": "MMR 的 append 只往後加、從不改寫既有節點：新項以高度 0 進來，遇到同高度的既有 peak 就合併升高，於是 peak 集合對應項數的二進位表示。這帶來兩個對 JAM 關鍵的性質——單次 append 只碰 O(log n) 個節點，而且**舊的證明不會失效**，因為它依賴的節點沒有被改寫。accumulation output 正是「持續產出、由鏈外長期驗證」的資料，BEEFY（§18）對 β_H 最後一筆的 super-peak 簽名，讓第三方能拿一份幾個月前的證明回來驗。普通平衡樹每加一片葉子就要重算整棵樹，所有舊證明全部作廢。",
 "optNotes": [
  "peak 合併規則與 append-only 帶來的舊證明有效性，正是選 MMR 的兩個理由。",
  "MMR 不重新平衡；而且 BEEFY 的消費者要驗的常常是舊區塊的輸出，不是只驗最新一筆。",
  "退化成 hash chain 的話，證明某一項要走過它之後的所有項，長度是 O(n) 而不是 O(log n)。",
  "環狀緩衝會讓舊輸出被覆蓋、證明永久失效；那是 ω 與 ξ 的做法，不是 belt 的做法。",
 ],
},
{
 "id": "ch11-assurance-signature",
 "ch": "11", "section": "11.2 Assurances",
 "gpRef": "§11.2", "difficulty": 2, "kind": "concept",
 "tags": ["assurance", "availability", "signature"],
 "stem": "An assurance carries a bitfield with one bit per core plus a signature. What is actually signed, and what would break if the signature covered only the bitfield?",
 "options": [
  "The signature covers a domain-separated hash of the parent header hash together with the encoded bitfield; without the parent hash the same signed bitfield could be replayed into a later block, letting a validator be counted as assuring data it no longer holds",
  "The signature covers only the bitfield, and replay is prevented by the on-chain rule that each validator may appear at most once per block; binding a block would be redundant because the extrinsic is already inside the block being signed",
  "The signature covers the work-report hashes of every core whose bit is set, so an assurer commits to specific reports; the parent header hash is not involved because reports outlive the block in which they were guaranteed",
  "The signature covers the assurer's own validator index and the bitfield, which is what lets the chain attribute the assurance; the parent hash is checked separately by comparing it against the header rather than by being signed",
 ],
 "answer": 0,
 "explanation": "§11.2 的 assurance 簽的是 domain separator 接上「parent header hash 與編碼後 bitfield 的 hash」。綁 parent hash 的用意是把這份表態鎖在**某一個特定的鏈上位置**：少了它，同一份簽名可以被別人撿去塞進之後任何一塊，讓一個早就把 shard 丟掉、甚至已經離線的 validator 持續被計入可得性門檻——而可得性門檻正是「資料還救得回來」的唯一保證。用 bitfield 而不是逐份報告簽名，則是頻寬考量：一個 validator 每塊可能同時持有數百個 core 的 shard，逐一簽名的驗簽成本是 C 倍。",
 "optNotes": [
  "綁 parent header hash 是為了防重放，這正是它被納入簽章輸入的理由。",
  "「每塊最多出現一次」擋得住同一塊內的重複，擋不住把舊簽名搬到後面的區塊。",
  "assurance 表態的是「我持有這些 core 的 shard」，不對特定 report hash 簽名——這正是 bitfield 的設計。",
  "validator index 由 extrinsic 欄位攜帶並用來取公鑰驗簽，不是靠簽章內容來歸屬。",
 ],
},
{
 "id": "ch14-oversize-rule",
 "ch": "14", "section": "14.4 Work Result Size",
 "gpRef": "§14; eq. 11.x (W_R)", "difficulty": 2, "kind": "concept",
 "tags": ["work-report", "oversize", "limits"],
 "stem": "A work-package's items refine one after another and the report has a size ceiling W_R. Is the ceiling applied per item or to the report as a whole, and what happens to an item that would cross it?",
 "options": [
  "It is cumulative: each item's output is measured against the authorizer trace plus the outputs already accepted, and the first item that would cross W_R has its output replaced by the OVERSIZE error while later items are still refined normally",
  "It is per item: each output is compared against W_R on its own, so a package can only fail if a single item is oversized; the report as a whole is unbounded because the bundle, not the report, is what availability has to carry",
  "It is cumulative, but crossing the ceiling invalidates the entire work-report, so the guarantors must drop the package and none of its items are reported — this is what stops a service from padding its output to squeeze others out",
  "It is cumulative and the outputs are truncated rather than replaced, with the truncation length recorded in the digest so that an auditor re-running refine can reproduce exactly the same bytes",
 ],
 "answer": 0,
 "explanation": "大小檢查是**累計**的：判斷的量是 authorizer trace |t| 加上先前已被接受的輸出總和，再加上這一項的輸出，超過 W_R 的第一項就把它的 result 換成 ⊖ OVERSIZE。關鍵有兩點——被換掉的是**該項的結果**，不是整份報告作廢（後面的 item 照跑，可能還是成功的）；而且順序有意義，同樣一組 item 換個順序，出事的可能是不同的那一個。這也是為什麼 OVERSIZE 屬於 𝔼 錯誤集合而不是「報告無效」：它是一個可被記錄、可被 accumulate 看到的結果，服務端能自己處理。",
 "optNotes": [
  "累計判斷、第一個越界的項被換成 OVERSIZE、後續照跑，三點都對上 §14 的規則。",
  "若只逐項比對，四個各佔 W_R 八成的 item 就能組出遠超上限的報告，鏈上限制形同虛設。",
  "整份報告作廢的話，一個 item 的失控就能吃掉同包其他服務的工作，OVERSIZE 也就不必列進 𝔼。",
  "GP 沒有截斷語意；截斷會讓 refine 的輸出不再是純函數的完整結果，auditor 重跑的比對基準也會變模糊。",
 ],
},
{
 "id": "appA-fault-address-rule",
 "ch": "A", "section": "A.4 Memory & Page Faults",
 "gpRef": "eq. A.9", "difficulty": 2, "kind": "concept",
 "tags": ["pvm", "page-fault", "memory"],
 "stem": "A multi-octet store straddles two pages: the first is writable, the second is not allocated. What does the PVM report, and why is the reported address defined the way it is?",
 "options": [
  "A page fault carrying the page-aligned address of the lowest inaccessible octet touched by the access; aligning to the page is what makes the value something the host can act on — it is exactly the page the host must map before the program is resumed",
  "A page fault carrying the exact address of the first inaccessible octet, so the host learns precisely where the access stopped; the host is expected to align the value itself before mapping, since alignment is a host concern rather than part of the machine's semantics",
  "A panic, because an access that crosses a page boundary into unallocated memory is by definition malformed; page faults are reserved for accesses that lie wholly inside a single unmapped page and can therefore be satisfied by mapping one page",
  "A page fault carrying the base address of the page containing the start of the access, so that the whole access can be retried from a known-mapped position; the machine writes the accessible prefix first and resumes from the fault address",
 ],
 "answer": 0,
 "explanation": "eq. A.9 把 fault 的參數定義成「被觸及的位址中最低的那個不可存取位址，向下對齊到 Z_P = 2^12 的頁邊界」。兩個設計點值得講：第一，**回報的是頁而不是精確位址**，因為 host 唯一能做的補救就是把那一頁映射進來再續跑，給它一個頁位址剛好可以直接用；第二，page fault 是**可回復的退出理由**而不是 panic，因為 refine 要按需載入 import segment、accumulate 要按需取 storage，如果一開始就得把所有可能用到的資料塞進記憶體，work-package 會大到不可行。另外，跨頁存取不會先寫入可存取的那一半——整個存取要嘛完成、要嘛不發生，否則重跑不出同樣的記憶體狀態。",
 "optNotes": [
  "最低不可存取位址、向下對齊到頁邊界，正是 eq. A.9 的定義，理由也在「host 要映射的是一整頁」。",
  "精確位址對 host 沒有多餘用處，而 GP 明確把對齊寫進了公式，不是留給 host 做。",
  "跨頁存取不是 malformed；fault 本來就要處理「一部分可存取」的情形，否則按需載入無法運作。",
  "回報存取起點所在的頁會指到一個**已經映射好**的頁，host 照著做等於沒補救，而且部分寫入會破壞可重現性。",
 ],
},
{
 "id": "appA-jump-semantics",
 "ch": "A", "section": "A.3 Basic Blocks & Control Transfer",
 "gpRef": "§A.3; §A.5", "difficulty": 2, "kind": "concept",
 "tags": ["pvm", "control-flow", "gas"],
 "stem": "The PVM has both statically-resolved jumps and indirect jumps computed from a register. What extra conditions must an indirect target satisfy, and what would break in the gas model if they were dropped?",
 "options": [
  "An indirect target must be aligned, non-zero, inside the jump table and land on a basic-block start; without the block-start requirement a program could enter a block below its first instruction and execute it without the block's gas ever being charged",
  "An indirect target must merely lie inside the code blob and be aligned; block starts are not required because the machine re-derives the enclosing block from the program counter and charges that block on entry, so gas accounting is unaffected either way",
  "An indirect target must be the start of a function as recorded in the program's symbol table, which is what the jump table holds; the gas model is unaffected because indirect jumps carry their own gas cost as an immediate operand",
  "An indirect target only has to be a multiple of the page size, so that a jump can never straddle a page; gas is charged per instruction retired rather than per block, so where control lands has no bearing on the accounting",
 ],
 "answer": 0,
 "explanation": "靜態跳躍（jump / load_imm_jump）帶的是有號的 PC 相對位移，組譯期就能解析；間接跳躍（jump_ind / load_imm_jump_ind）的目標由暫存器算出，因此 GP 對它加了四個條件：對齊 Z_A、非零、落在 jump table 範圍內，而且 j[a/Z_A − 1] 必須是一個 **basic block 的起點**。最後一條跟 0.8.0 的 gas 模型直接相扣——gas 是在「進入 block」時整塊預扣的，如果可以從 block 中間切進去，那段指令就會在沒被計價的情況下執行，等於無限免費計算。對齊那條則是 GP 自己說的 LLVM 相容性：LLVM 產碼時假設動態跳躍目標有一定的對齊。",
 "optNotes": [
  "四個條件與「block 起點保證 gas 一定被收過」的關聯，正是這題要考的設計連動。",
  "PVM 不會在跳躍後回頭補收 block 的 gas；預扣發生在進入 block 的那一刻，所以落點必須受限。",
  "jump table 存的是合法跳躍目標，不是符號表；指令也沒有攜帶 gas 立即數。",
  "頁大小與控制流無關，而 0.8.0 早已不是每指令計價——這是 0.7.2 的模型。",
 ],
 "trap": "被問「為什麼間接跳躍要限制目標」時，先講 gas，再講 LLVM 對齊，順序反過來會顯得只背了條文。",
},
{
 "id": "appB-gas-model",
 "ch": "B", "section": "B.1 Host Call Gas",
 "gpRef": "§B（PR #517）", "difficulty": 2, "kind": "delta",
 "tags": ["host-call", "gas", "delta-0.8.0"],
 "stem": "GP 0.8.0 reworked how a host call is charged. Describe the shape of the new charge and what happens when a service invokes an index that is not available in its invocation.",
 "options": [
  "Each call has a base cost plus, where it moves data, a term proportional to the number of KiB touched; an index that is unknown or unavailable is charged a default cost first, so a call with too little gas left exits out-of-gas rather than returning an error code",
  "Each call costs the same flat amount regardless of the data it moves, which is what keeps a basic block's cost statically computable; an unknown index is free and simply returns WHAT, since charging for a call that did nothing would be unfair",
  "The cost is computed after the call from the gas the host actually consumed, so a call that moves more data naturally costs more; an unknown index returns WHAT and the machine charges nothing, leaving the counter untouched",
  "Costs are declared by the service in its metadata and validated at registration, which lets a service bound its own worst case; an unknown index aborts the whole accumulation with a panic so that mistakes surface loudly during development",
 ],
 "answer": 0,
 "explanation": "0.8.0（PR #517）把 host call 的計價改成「基本成本 + 資料量項」：每個呼叫有自己的 base cost，會搬資料的再加上按 KiB 計的部分。這件事的面試價值在它跟兩件事的互動——第一，**先扣後做**：不明或當前 invocation 不可用的 index 會先被收一筆預設成本，所以餘額不足時的結果是 ∞（out-of-gas，整個 invocation 收掉並回到 checkpoint），而不是乖乖回 WHAT，這是實作很容易寫反的地方；第二，它跟附錄 A 的 block-level 預扣是兩層獨立的計價，host call 的成本不會被算進 block 的 ϱ^Δ 裡。",
 "optNotes": [
  "base + 每 KiB、以及不明 index 先扣預設成本導致可能 OOG，兩點都是 0.8.0 的規定。",
  "0.8.0 已經不是齊頭式定價；而且 block 的靜態成本與 host call 的成本本來就分屬兩層。",
  "事後依實際消耗計價無法跨實作重現，等於放棄確定性——GP 的成本一律是規格寫死的。",
  "服務不能自訂 host call 價目；讓 service 宣告成本等於讓它自己決定攻擊成本。",
 ],
},
{
 "id": "appB-grow-heap-semantics",
 "ch": "B", "section": "B.2 grow_heap",
 "gpRef": "§B（PR #508 / #517）", "difficulty": 2, "kind": "delta",
 "tags": ["host-call", "memory", "delta-0.8.0"],
 "stem": "GP 0.8.0 removes the sbrk instruction and provides heap growth as the grow_heap host call instead. What does the caller pass, and why is a host call the right home for this operation under the 0.8.0 gas model?",
 "options": [
  "The caller names the heap end it wants and is charged in proportion to the pages newly made writable; an instruction whose cost depends on its operand would break the promise that a basic block's price can be computed statically before the block runs",
  "The caller passes the number of octets to add and is charged a flat amount; it was moved out of the instruction set purely for encoding space, since the opcode was needed for one of the new no-argument instructions introduced in 0.8.0",
  "The caller passes a page count and the call is free, because the memory was already reserved when the program was initialized; making it a host call simply lets the host refuse growth when the machine is nested inside an inner PVM",
  "The caller passes the desired end page and the cost is settled afterwards from the host's actual allocation cost, which is why it cannot be an instruction — instructions must have their cost known before they execute, but host calls are charged on return",
 ],
 "answer": 0,
 "explanation": "grow_heap 吃的是「想要的堆結尾頁」，費用按**新變成可寫的頁數**計。它從指令變成 host call 的理由跟 0.8.0 的 gas 模型直接相關：附錄 A 改成整個 basic block 在進入時預先扣款，而預扣的前提是 block 的價格能在執行前**靜態算出**。一條成本取決於運算元的指令會讓這個前提破掉——你無法在不執行的情況下知道這次 sbrk 要長多少頁。搬成 host call 之後，指令層維持靜態可計價，動態成本統一走 host call 那條先扣後做的路徑。",
 "optNotes": [
  "指定結尾頁、按新增頁數計費，理由落在「block 價格必須靜態可算」，這正是 0.8.0 的連動。",
  "動機不是編碼空間；把它留在指令集裡會直接破壞 block-level 預扣的前提。",
  "記憶體不是初始化時就全部保留，否則 grow_heap 沒有存在意義，也不會需要計費。",
  "host call 同樣是先扣後做，不是事後結算——事後結算無法保證跨實作一致。",
 ],
},
{
 "id": "appB-fetch-purpose",
 "ch": "B", "section": "B.2 fetch",
 "gpRef": "§B", "difficulty": 2, "kind": "concept",
 "tags": ["host-call", "refine", "design"],
 "stem": "fetch is a single host call, available in all three invocations, whose first argument selects which piece of data to read. Why did the GP fold this many data sources into one call instead of giving each its own index?",
 "options": [
  "Because the host-call numbering is part of the ABI every deployed service compiles against: a selector argument lets new data sources be added without renumbering anything, while a new index per source would eventually force existing services to be rebuilt",
  "Because each invocation exposes a different subset of the sources, and a single call is the only way to express that — with separate indices the machine could not tell which ones are legal in refine as opposed to accumulate",
  "Because the sources share one gas price, and the GP charges per host-call index; folding them together is what keeps the price of reading the protocol constants identical to the price of reading a work-package's imports",
  "Because a selector keeps the call's register signature within the four argument registers available to host calls, which separate indices could not do since each source needs its own offset and length pair",
 ],
 "answer": 0,
 "explanation": "fetch 用 φ_10 當 selector 選資料來源（協定常數、entropy、authorizer trace、extrinsic 與 import、work-package 各部分…），三種 invocation 都能用，只是可取的來源不同。把它們收成一個呼叫的理由是 **ABI 穩定性**：host call 的編號是所有已部署 service 編譯時就寫死的介面，每加一種資料就配一個新編號，遲早會撞上重新編號的需求，而重新編號會讓既有 service 全部失效（0.8.0 移除 sbrk 導致 opcode 位移就是同一類痛）。selector 是資料層的參數，加東西只要多一個值。",
 "optNotes": [
  "ABI 穩定、加來源不必動編號，正是把多來源收進單一 fetch 的理由。",
  "「哪些來源在哪個 invocation 可用」用個別編號一樣表達得出來——那只是 dispatch 表的事。",
  "同一個 fetch 的不同來源本來就可能因搬運資料量而價格不同，不是齊頭定價。",
  "暫存器數量不是限制：每個來源本來就只需要 selector 加上輸出緩衝的位址與長度。",
 ],
},
{
 "id": "appC-digest-error-encoding",
 "ch": "C", "section": "C.x Work Digest",
 "gpRef": "§C；eq. 11.7（𝔼）", "difficulty": 2, "kind": "concept",
 "tags": ["codec", "work-digest", "errors"],
 "stem": "A work digest's result field holds either the refine output or a member of the error set 𝔼. How is that alternative encoded, and why does the GP put refine failures on-chain as values rather than rejecting the report?",
 "options": [
  "Success is a discriminant octet followed by the length-prefixed blob, and each error is a single distinct octet; keeping failures as ordinary values lets accumulate see exactly how an item failed, and lets one item fail without invalidating the others in the package",
  "Success and failure share the same shape — a length-prefixed blob, empty in the failure case — with the reason carried separately in the report's authorizer trace; this keeps the digest fixed-width, which the erasure coder relies on",
  "Errors are encoded as reserved blob values that no successful refine can produce, so no discriminant is needed; a report containing any error is still valid but is skipped by accumulate, which is why the error variants need no on-chain meaning",
  "A failing item makes the whole work-report invalid, so the encoding has no error case at all; the 𝔼 set exists only to name the conditions guarantors check off-chain before deciding whether to sign the report",
 ],
 "answer": 0,
 "explanation": "digest 的 result 用一個判別位元組區分：成功是判別值再接長度前綴的 blob，失敗則是單一個位元組，各自對應 𝔼 裡的 ∞（out-of-gas）、☇（panic）、BADEXPORTS、OVERSIZE、BAD、BIG。把失敗當**值**而不是當「報告無效」是刻意的：第一，accumulate 讀得到失敗原因，服務可以自己決定要重試、退款還是記帳；第二，同一個 work-package 裡其他 item 不受牽連，否則一個服務的失控就能吃掉同包所有人的工作；第三，失敗也要被稽核——auditor 重跑時比對的是「同一個輸入是否同樣失敗」，若失敗不上鏈就沒有可比對的對象。",
 "optNotes": [
  "判別位元組 + 單位元組錯誤碼，以及「失敗是值」帶來的三個好處，正是 GP 的設計。",
  "空 blob 無法區分「成功但輸出為空」與「失敗」，而 digest 本來就不是固定寬度。",
  "保留值的做法會讓錯誤與合法輸出混淆；而且 accumulate 確實看得到錯誤，不是跳過。",
  "單一 item 失敗不會讓整份報告無效——OVERSIZE 之所以列在 𝔼 裡就是因為它是可記錄的結果。",
 ],
},
{
 "id": "ch06-fallback-purpose",
 "ch": "6", "section": "6.5 The Slot Key Sequence",
 "gpRef": "eq. 6.25–6.26", "difficulty": 2, "kind": "concept",
 "tags": ["safrole", "fallback", "anonymity"],
 "stem": "When too few tickets arrive, γ′_S falls back to a key sequence derived from entropy and the active validator set. How is each slot's author chosen, and what property does the chain give up while the fallback is in force?",
 "options": [
  "Each slot's author is picked by hashing the entropy together with the slot index and reducing the result modulo the set size; the whole epoch's schedule becomes publicly computable in advance, so the anonymity that ring VRF tickets buy is lost for that epoch",
  "Each slot's author is the validator whose index equals the slot number modulo the set size, so the schedule is a plain round robin; nothing is lost beyond fairness, since a round robin gives some validators marginally more slots than others",
  "Authors are drawn from the previous epoch's ticket accumulator, reusing the newest tickets that were not consumed; anonymity is preserved because those tickets are still ring-VRF proofs, but liveness suffers because the pool eventually empties",
  "The fallback assigns every slot to the validator set collectively and accepts the first valid seal to arrive; anonymity is unaffected because no schedule exists, at the cost of occasional competing blocks at the same height",
 ],
 "answer": 0,
 "explanation": "fallback 對每個 slot i 取 entropy 與 slot 索引一起 hash、截取四個位元組解成整數後對 validator 數取模，選出該 slot 的出塊者。它的代價很具體：所需的輸入在 epoch 一開始就全部公開，任何人都能把**整個 epoch 的出塊表**算出來——這正是 ring VRF ticket 花力氣買來的匿名性，在 fallback 生效期間完全消失，針對性 DoS 與賄賂重新變得可行。GP 仍然這樣設計，是因為可用性優先於匿名性：寧可退化也不要停鏈。Y = 500 的投票截止線就是為了讓票源有時間累積、盡量不走到這條路。",
 "optNotes": [
  "hash(entropy ⌢ slot index) 取模選人、以及匿名性全失，兩者是 eq. 6.26 與其代價。",
  "純輪流會讓出塊順序與 validator 索引綁死，任何人都能長期預測，且無法隨 entropy 變動。",
  "fallback 的前提就是票不夠，沒有可重用的票；重用舊票也會讓同一張票決定兩個 epoch。",
  "無排程、先到先得等於放棄單一出塊者，會讓每個 slot 都可能分叉，與 Safrole 的目的相反。",
 ],
 "trap": "「票不夠會怎樣」要答到「出塊表變成公開可算」，只說「用公鑰輪流」等於沒答到重點。",
},
]