# -*- coding: utf-8 -*-
# §5 The Header — additional oral-interview items (written for the team's chapter-5 discussion).
ITEMS = [
{
 "id": "ch05-parent-hash-covers-seal",
 "ch": "5", "section": "5.1 The Header",
 "gpRef": "eq. 5.2", "difficulty": 2, "kind": "concept",
 "tags": ["header", "parent-hash", "seal"],
  "stemZh": "H_P 被定義為父 header 某種編碼的 Blake2b 雜湊。被雜湊的是哪一種編碼？這個選擇帶來什麼後果？",
  "optionsZh": [
   "完整編碼，含父區塊的 seal，所以子區塊承諾的是父區塊實際被發布出去的那串位元組；任何人都無法重簽一個 header——即使作者與內容都相同——而不讓所有已經建在其上的區塊脫鏈",
   "未簽署的編碼，讓父區塊的 seal 留在承諾鏈之外；這使得 validator 可以替換遺失的 seal 而不干擾其後代，這正是無 seal 封存儲存得以成立的原因",
   "完整編碼，但把 marker 清成空的形式，好讓同一個父區塊不論是否開啟了一個 epoch 都得到同一個雜湊；這讓雜湊在 marker 較晚才加入的 epoch 邊界上保持穩定",
   "只雜湊父區塊的 state root 與時槽，因為這兩個欄位已經唯一決定了父區塊；雜湊整個 header 會讓這個承諾依賴於子區塊無法獨立重建的資料"
  ],
  "stem": "H_P is defined as the Blake2b hash of an encoding of the parent header. Which encoding is hashed, and what follows from that choice?",
 "options": [
  "The full encoding including the parent's seal, so a child commits to the exact sealed bytes its parent was published as; nobody can re-seal a header — even with the same author and contents — without orphaning every block already built on it",
  "The unsigned encoding, so that the parent's seal stays outside the chain of commitments; this lets a validator replace a lost seal without disturbing its descendants, which is what makes seal-less archival storage possible",
  "The full encoding, but with the markers cleared to their empty forms, so that the same parent yields one hash whether or not it opened an epoch; this keeps hashes stable across the epoch boundary where markers are added late",
  "A hash of the parent's state root and timeslot only, since those two fields already determine the parent uniquely; hashing the whole header would make the commitment depend on data the child cannot independently reconstruct",
 ],
 "answer": 0,
 "explanation": "eq. 5.2：H_P ≡ Blake2b(E(P(H)))。這裡 P(H) 是父 header，E 是**完整**編碼——含 seal H_S 的那一版。GP 為 header 定義了兩個序列化函數：E(H) 含 seal、E_U(H) 不含（「with and without the latter seal component」），而 **E_U 的用途只有一個：當 seal 自己要簽的訊息**。父雜湊用的是 E，不是 E_U。**推論**：每個子區塊都把父區塊「實際發布出去的那串位元組」原封釘死。改動父 header 的任何一個位元組——包括用同一把金鑰對同樣的內容重簽一次 seal——都會算出不同的 H_P，讓所有已經建在上面的區塊瞬間脫鏈。這正是「鏈」這個字的意思，也是為什麼 seal 必須是 header 的欄位，而不是掛在旁邊的附屬資料：若父雜湊只涵蓋 E_U，同一份內容就能被簽出多個都合法的父節點，等於憑空製造分叉。**順帶記兩件相關的事**：§5 用 P 定義祖先集合 A（h ∈ A ⇔ h = H ∨ ∃i ∈ A : h = P(i)），但實作只被要求保存「過去 24 小時（L = 14,400 個時槽）內出塊的祖先 header」——所以「能不能往回追」是有窗口的，這個窗口後來在 §11 的 lookup-anchor 檢查會再出現一次。",
 "optNotes": [
  "完整編碼（含 seal）與「重簽即脫鏈」的推論，正是 eq. 5.2 的直接後果。",
  "E_U 是簽章訊息，不是父雜湊的輸入；若不涵蓋 seal，同一份內容可以被重複簽出多個合法父節點。",
  "GP 沒有「清空 marker 再雜湊」的變體；marker 是在出塊當下就決定的欄位，不會事後補。",
  "只雜湊兩個欄位會讓不同 header 碰撞成同一個 H_P，等於允許替換父區塊的其餘內容。",
 ],
},
{
 "id": "ch05-what-header-alone-proves",
  "alsoCh": ["6"],
 "ch": "5", "section": "5.1–5.3",
 "gpRef": "§5; eq. 5.8; eq. 5.9", "difficulty": 3, "kind": "concept",
 "tags": ["header", "light-client", "validation"],
  "stemZh": "一個節點只收到一個 header，既沒有區塊本體也沒有任何鏈上狀態。它能完成哪些檢查？第一個做不到的又是哪一個？",
  "optionsZh": [
   "它能檢查結構是否完整、時槽是否大於父區塊的、以及該時槽是否未落在未來；它無法驗證 seal，因為要知道誰有資格出那一槽，需要 sealer 序列，而它住在狀態裡",
   "除了 extrinsic 雜湊之外它什麼都能檢查，因為只有那個欄位依賴 header 之外的資料；seal 是自足的，因為出塊者的公鑰本身就是 header 的欄位之一、不需要任何外部查找",
   "它能檢查 seal 與熵簽章，因為兩者光憑出塊者索引就能驗證；它無法檢查的是時槽，因為要與父區塊比較就必須保存過父 header",
   "沒有狀態它什麼都檢查不了，因為連時槽的界限都是對著 posterior 的 validator 集合表述的；這正是為什麼 GP 要求實作在驗證任何 header 之前先保存 24 小時的祖先"
  ],
  "stem": "A node receives only a header, with neither the block body nor any chain state. Which checks can it complete, and which one is the first that it cannot?",
 "options": [
  "It can check structural well-formedness, that the timeslot exceeds its parent's, and that the slot is not in the future; it cannot verify the seal, because knowing who was entitled to author that slot requires the sealer sequence, which lives in state",
  "It can check everything except the extrinsic hash, since only that field depends on data outside the header; the seal is self-contained because the author's public key is one of the header's own fields and needs no external lookup",
  "It can check the seal and the entropy signature, since both are verifiable against the author index alone; what it cannot check is the timeslot, because comparing against the parent requires having stored the parent header",
  "It can check nothing without state, because even the timeslot bound is expressed against the posterior validator set; this is why the GP requires implementations to keep 24 hours of ancestors before validating any header",
 ],
 "answer": 0,
 "explanation": "把檢查按「需要什麼才做得到」分三層就很清楚。**只要 header 自己**：結構檢查——eq. 5.1 的 header 是 10 元組 (H_P 父雜湊, H_R 先前狀態根, H_X extrinsic 雜湊, H_T 時槽, H_E, H_W, H_O 三個 marker, H_I 作者索引, H_V 熵 VRF 簽章, H_S seal)，欄位數、型別與長度都能就地驗。**要父 header 或時鐘**：eq. 5.8 的時間條件 P(H)_T < H_T ∧ H_T · P ≤ 𝕋。這裡 P(H) 是父 header（存過那張 header 即可，不必有狀態）、P = 6 是每個時槽的秒數、𝕋 是牆鐘時間；前半只要父 header，後半只要一個時鐘。GP 還補一句「blocks considered invalid by this rule may become valid as 𝕋 advances」——「太未來」是暫時無效，不是永久無效。**要狀態**：seal。而且 H_S 是雙重狀態相依。其一，header 只放 H_I（索引），不放公鑰；§5 原文特別註明 H_A ≡ κ′[H_I]_b 「is merely an equivalence, and is not serialized as part of the header」，要拿驗簽用的 Bandersnatch 公鑰就得查 κ′。其二，就算有了公鑰還要確認「這個 slot 本來就該由他出塊」：§6 定義 H_S 是「a Bandersnatch signature produced with the private key corresponding to the entry at index m′ of the current epoch’s slot-sealer sequence γ′_S」，m′ 是本塊在 epoch 內的 slot phase。κ′ 與 γ′_S 都是狀態。相關名詞（站上「名詞」模式都查得到）：validator 金鑰有四組——κ active（現任）、λ previous（上一輪）、ι staging（待命）、γ_P pending（下個 epoch 生效）；γ_S 是 slot-sealer sequence，票券模式下每格是一張 ticket、fallback 模式下每格直接是 Bandersnatch 公鑰；E_U(H) 是「不含 H_S 的 header 編碼」，也就是 seal 實際簽的那段訊息。**這題真正的落點**：正因為 seal 需要狀態，header 才要帶 marker。H_E 在每個 epoch 第一塊給出下個 epoch 的 entropy 與整組 validator 金鑰、H_W 在票券截止那一塊給出整個 epoch 的 600 張 ticket。只同步 header 鏈的輕客戶端因此能自行推出 κ′ 與 γ′_S 的變化、往後一路驗 seal，不必重放狀態——§6 說得很直接，marker 存在是為了「minimize data transfer necessary to determine the validator keys associated with any given epoch」。",
 "optNotes": [
  "結構與時間可查、seal 需要 sealer 序列（狀態）——這正是 marker 存在的理由。",
  "作者的公鑰不是 header 欄位：H_I 是索引，H_A ≡ κ′[H_I]_b 只是等價式，不被序列化。",
  "驗簽反而是最需要外部資訊的一步；而時間檢查只需要父 header 與時鐘。",
  "24 小時祖先的要求是為了 anchor 檢查，不是時間條件的前提；時間條件不涉及 κ′。",
 ],
 "trap": "「拿到 header 你能驗什麼」是很常見的開場題，答案的分水嶺在「簽章需要狀態」。",
},
{
 "id": "ch05-genesis-presumed",
 "ch": "5", "section": "5.1 The Header",
 "gpRef": "§5（genesis header 與 σ_g）", "difficulty": 2, "kind": "rationale",
 "tags": ["header", "genesis", "trust"],
  "stemZh": "GP 說對 genesis header 及其所代表狀態的共識是預設而非推導出來的。為什麼一個鏈的定義非得包含這樣一個假設不可？",
  "optionsZh": [
   "因為每個 header 的有效性都是相對於它的父區塊定義的，所以這條遞迴需要一個在鏈外達成共識的基底；沒有基底的話，任何自洽的鏈都會和其他鏈一樣有效，「這條」鏈也就沒有明確定義",
   "因為 genesis 狀態太大，無法用後續區塊所用的同一個函數來 Merklize，所以它的 root 必須另外公布並暫且信任，直到第一個真正的區塊建立起常規的不變式",
   "因為 genesis 區塊沒有出塊者、因而沒有 seal，而 GP 的有效性規則只針對已封印的 header 陳述；預設 genesis 是一種記號上的捷徑，正式的鏈會用一個 genesis seal 來取代它",
   "因為 genesis 時的 validator 集合無法被承諾在它本應授權的那份狀態之內，所以啟動用的金鑰是由 chain spec 分發的，而 state root 由每個節點自行從那個檔案重算"
  ],
  "stem": "The GP says consensus over the genesis header and the state it represents is presumed rather than derived. Why must a chain definition contain such an assumption at all?",
 "options": [
  "Because every header's validity is defined relative to its parent, so the recursion needs a base case that is agreed out-of-band; without one, any self-consistent chain would be as valid as any other and 'the' chain would not be well defined",
  "Because the genesis state is too large to Merklize with the same function used for later blocks, so its root has to be published separately and taken on trust until the first real block establishes the normal invariants",
  "Because the genesis block has no author and therefore no seal, and the GP's validity rules are stated only for sealed headers; presuming genesis is a notational shortcut that a production chain replaces with a genesis seal",
  "Because the validator set at genesis cannot be committed to inside the state it is meant to authorize, so the bootstrap keys are distributed by the chain spec and the state root is recomputed by each node from that file",
 ],
 "answer": 0,
 "explanation": "§5 直接寫明：對 genesis header H_g 與它所代表的狀態 σ_g 的共識是**預設（presumed）**的，不是推導出來的。**形式上的理由是遞迴需要基底。** header 的合法性全部是相對於父 header 定義的——H_P ≡ Blake2b(E(P(H))) 指向父、eq. 5.8 要求 H_T 嚴格大於父的 H_T、seal 要用父之後的狀態才驗得了。這是一條往回追的遞迴，而遞迴不能無限往回，必須有一個不靠同一套規則產生的起點。若沒有這個起點，任何一條內部自洽的鏈都同樣「合法」，「**這條**鏈」這四個字就失去指涉——你無法只用協定規則區分主網與某人昨天在筆電上生出來的鏈。**實務上這個基底就是 chain spec**：所有節點在鏈外（透過發行、社群、程式碼中寫死的檔案）同意同一份 genesis header 與 genesis state，之後每一件事才能靠密碼學推導。JIP-4 定義的 `protocol_parameters` 就是這份 chainspec 的一部分。**注意這不是 JAM 特有的妥協**，任何區塊鏈都有同一個公理；GP 只是把它明講出來，而不是假裝 genesis 也是被驗證的。也要分清楚：被預設的是「哪一份 genesis 算數」這個社會共識，不是它的內容不能被檢查——σ_g 用的是跟其他所有狀態一樣的 Merklization 函數 M_σ，算得出 root，只是沒有更早的區塊能為它背書。",
 "optNotes": [
  "遞迴需要鏈外約定的基底，這是 genesis 被「預設」而非「推導」的形式理由。",
  "genesis 狀態用的是同一個 Merklization 函數，大小不是問題。",
  "把它說成暫時的notation 捷徑並不正確——任何鏈都需要這個公理，不會被 genesis seal 取代。",
  "驗證者集合本來就存在 genesis 狀態裡；問題不在能不能放，而在誰來認定那份狀態。",
 ],
},
{
 "id": "ch05-why-five-component-hash",
 "ch": "5", "section": "5.2 The Extrinsic Hash",
 "gpRef": "eq. 5.4–5.7", "difficulty": 3, "kind": "rationale",
 "tags": ["header", "extrinsic-hash", "light-client"],
  "stemZh": "H_X 雜湊的是五個各成分雜湊所組成的序列，而其中兩個成分的內部又把每一項各自化約成一個雜湊。這種形狀買到了什麼？為什麼只有那兩個被這樣處理？",
  "optionsZh": [
   "它讓第三方能夠證明某一份 preimage 或某一份 guarantee 被納入，而不必交出 extrinsic 的其餘部分；因此那些「外界會在意個別項目」的成分被逐項化，其餘的則整批承諾",
   "它讓五個成分可以彼此獨立地被傳播與驗證，這正是 validator 能夠接受某個區塊的 assurance、同時仍在等待它的 guarantee 從網路上抵達的原因",
   "它讓某個成分改變時重算雜湊變得便宜，所以正在組裝區塊的出塊者可以換上一組更好的 guarantee，而不必重新雜湊已經定案的 ticket、assurance 與 dispute",
   "它限制了 extrinsic 的大小，因為一個逐項雜湊的成分可以對照逐項的上限來檢查，而單一份扁平編碼會讓鏈上的有效性規則看不到那個上限"
  ],
  "stem": "H_X hashes a sequence of five per-component hashes, and inside two of those components each item is itself reduced to a hash. What is that shape buying, and why are only those two treated that way?",
 "options": [
  "It lets a third party prove one preimage or one guarantee was included without shipping the rest of the extrinsic, so the components whose individual items outsiders care about are itemized while the others are committed to wholesale",
  "It lets the five components be gossiped and verified independently of one another, which is what allows a validator to accept the assurances of a block while still waiting for its guarantees to arrive over the network",
  "It keeps the hash cheap to recompute when one component changes, so an author assembling a block can swap in a better set of guarantees without rehashing the tickets, assurances and disputes it has already fixed",
  "It bounds the size of the extrinsic, because a component that hashes its items individually can be checked against a per-item limit that a single flat encoding would hide from the on-chain validity rules",
 ],
 "answer": 0,
 "explanation": "H_X = H(E(H#(a)))，a 是五個 extrinsic 分量各自的雜湊。**這是一棵極扁的證明樹**：想證明某個 preimage 被納入，只要出示另外四個分量的雜湊，加上 p 這個分量的內容即可——其他四份資料（可能包含整包 guarantee 與 ticket）完全不必給。**為什麼只有 p 與 g 內部再逐項雜湊**：GP 的原話是這個設計「taking care to allow for the possibility of reports and preimages to individually have their inclusion proven」。關鍵在「individually」——外界真正會**單獨追問**的就是這兩種東西：某份 preimage 有沒有上鏈（service 要據此確認自己請求的資料已就位）、某份 report 有沒有被擔保（下游 package 要引用它的 exports root）。所以 p 存 (E_4(service), H(data))、g 存 (H(report), E_4(slot), var(credential))，**只放雜湊就足以證明存在，而不必搬運可能達數十 KB 的內容**。**其他三個為什麼整包編碼就好**：ticket、assurance、dispute 沒有「第三方要單獨證明某一筆存在」的需求——它們是鏈內部的表態，驗證者本來就會拿到整包。**通則**：承諾結構的細緻程度跟隨證明需求走，而不是一律做到最細——每多一層都是額外的雜湊成本，沒人要用的證明能力就是浪費。",
 "optNotes": [
  "為個別 preimage 與 report 提供包含證明，正是 GP 對這個結構寫下的理由。",
  "H_X 是事後的承諾，與分量能不能各自傳播無關；區塊本來就是整體被驗證的。",
  "重算成本不是動機：出塊者本來就要把整份 extrinsic 定下來才能封塊。",
  "大小限制寫在 §11 的 W_R 等規則裡，不靠雜湊結構表達。",
 ],
},
{
 "id": "ch05-epoch-marker-content",
 "ch": "5", "section": "5.3 The Markers",
 "gpRef": "eq. 5.11；§6.6", "difficulty": 2, "kind": "concept",
 "tags": ["header", "markers", "epoch"],
  "stemZh": "當一個區塊是某個新 epoch 的第一塊時，它的 epoch marker 會被填入內容。這個 marker 帶什麼？又是給誰用的？",
  "optionsZh": [
   "下一個與當前 epoch 的隨機數，加上接下來那個 epoch 每位 validator 的 Bandersnatch 與 Ed25519 金鑰——足夠讓只讀 header 的追隨者重建出誰可以出塊、並驗證他們的簽章",
   "上一個 epoch 最終狀態的雜湊，以及 ticket accumulator 在邊界時的樣子，好讓追隨者能自行重放那場 ticket 競賽、確認 sealer 序列是誠實導出的",
   "完整的下一個 epoch slot-sealer 序列，這也是為什麼這個 marker 是 optional 的——若每個 header 都帶，成本會是每塊 600 筆而不是每個 epoch 一次",
   "離開與加入的 validator 身分，以相對於前一個集合的差異表示，並附上將為接下來那個 epoch 的洗牌播種的熵"
  ],
  "stem": "When a block is the first of a new epoch, its epoch marker is populated. What does that marker carry, and who is it for?",
 "options": [
  "The next and current epoch randomness plus, for every validator of the coming epoch, its Bandersnatch and Ed25519 keys — enough for a header-only follower to reconstruct who may author and to verify their signatures",
  "The hash of the previous epoch's final state and the ticket accumulator as it stood at the boundary, so that a follower can replay the ticket contest itself and confirm the sealer sequence was derived honestly",
  "The next epoch's slot-sealer sequence in full, which is why the marker is optional — carrying it in every header would cost 600 entries per block rather than one per epoch",
  "The identities of validators leaving and joining, expressed as a delta against the previous set, together with the entropy that will seed the coming epoch's shuffle",
 ],
 "answer": 0,
 "explanation": "型別在 eq. 5.11：H_E ∈ ?(H, H, ⟦(bskey, edkey)⟧_V)，內容由 eq. 6.28 定義為 (η_0, η_1, [(k_b, k_e) | k ∈ γ′_P])。**兩個隨機數是 prior 的 η_0 與 η_1**（rotate 之後成為 η′_1、η′_2），而 η′_2 正是下個 epoch 抽 ticket 與 fallback 要用的種子——marker 等於提前公告抽籤用的隨機性。**金鑰是 γ′_P（pending set）的**，每位 validator 給兩把：Bandersnatch 用來驗未來的 seal，Ed25519 用來驗 guarantee、assurance 與 judgment 的簽章。**受眾是只同步 header 的人**：validator set 換人之後，後續所有簽章都要用新金鑰驗，而金鑰住在狀態裡；把它放進 header，輕客戶端才能在不重放狀態的前提下一路驗下去。**兩個常見混淆**：其一，600 張 ticket 是**另一個** marker（H_W）的內容，不在 H_E 裡；H_E 給的是「誰有資格」，H_W 給的是「哪個 slot 輪到誰」。其二，**BLS 金鑰不在裡面**——它只用於 Beefy 的鏈下分發，對「跟著 header 走」沒有用處，給了是浪費頻寬。",
 "optNotes": [
  "兩個隨機數加上全套下屆金鑰、服務對象是只看 header 的追隨者，正是 §6.6 的定義與用途。",
  "GP 沒有把 ticket accumulator 放進 marker；讓追隨者自行重跑抽籤等於要它持有狀態。",
  "600 張 ticket 是 winning-tickets marker H_W 的內容，不是 epoch marker。",
  "marker 給的是完整金鑰列表而非差異；差異式表示法要求接收者已經握有前一屆的完整集合。",
 ],
},
{
 "id": "ch05-index-not-key",
 "ch": "5", "section": "5.1 The Header",
 "gpRef": "eq. 5.10", "difficulty": 2, "kind": "rationale",
 "tags": ["header", "author", "design"],
  "stemZh": "header 以索引而非公鑰來標識它的出塊者。除了省下位元組之外，這個選擇強制了什麼？代價又是什麼？",
  "optionsZh": [
   "它強制每位驗證者事先就對 posterior 的 active set 有共識，因為索引離開它就沒有意義；代價是一個 header 無法被孤立地解讀，而這正是 epoch marker 存在的原因",
   "它強制出塊者另外證明集合成員資格，因為光憑一個索引無法拿去對照簽章；代價是每塊多一份 ring proof，這也是 seal 與熵簽章各自獨立的原因",
   "它強制 validator 集合依公鑰排序好讓索引具有正規性；代價是集合一變動所有索引都會重排，這也是為什麼 offender 是就地歸零而不是被移除",
   "它強制索引在 disputes 之後重新導出，因為被懲罰者的位置會被重複使用；代價是同一個 epoch 內的兩個區塊可能合法地為不同的出塊者帶著相同的索引"
  ],
  "stem": "The header identifies its author by an index rather than by a public key. Beyond saving bytes, what does that choice force, and what does it cost?",
 "options": [
  "It forces every verifier to already agree on the posterior active set, since the index means nothing without it; the cost is that a header cannot be interpreted in isolation, which is precisely why the epoch marker exists",
  "It forces the author to prove set membership separately, since an index alone cannot be checked against a signature; the cost is an extra ring proof per block, which is why the seal and the entropy signature are distinct",
  "It forces the validator set to be ordered by public key so that indices are canonical; the cost is that a set change reorders every index, which is why offenders are zeroed in place rather than removed",
  "It forces the index to be re-derived after disputes, since a punished validator's slot is reused; the cost is that two blocks in the same epoch may legitimately carry the same index for different authors",
 ],
 "answer": 0,
 "explanation": "eq. 5.10：H_I ∈ N_{|κ′|}，而 H_A ≡ κ′[H_I]_b **只是等價式、不被序列化**。**省 32 個位元組只是表面**。真正的效果是：它把「這個 header 說的是誰」變成一個**相對於 κ′ 的問題**。索引本身不帶任何資訊——同一個 H_I = 3 在不同 epoch 指向不同的人。於是任何驗證者都必須**先同意同一份 posterior active set**，才能解讀這個 header。**代價就是 header 不能被單獨解讀**，而這正是 epoch marker 存在的理由：validator set 換人時，把新的金鑰序列放進 header，讓只看 header 的人也能跟上索引的意義。兩個設計是配套的——用索引省下的頻寬，一部分又還給了 marker，但 marker 每個 epoch 只出現一次，索引則是每塊都省，整體仍然划算。**實作上還有一個直接後果**：H_I 的上界是 **|κ′| 而不是 |κ|**，兩者只有在集合大小不變時才等價——0.8.0 讓 |κ| 可變之後這個區別變得實質。fuzzer bug #825 就踩在這裡：一個 H_I = 65535 的 header 在還沒做界限檢查前就被拿去索引，直接 panic。",
 "optNotes": [
  "索引把解讀權綁在 κ′ 上、因而需要 epoch marker，這是這個設計最實質的連動。",
  "seal 本身就是用 κ′[H_I] 的金鑰驗的，不需要額外的成員資格證明；ring proof 用在 ticket，不在 seal。",
  "GP 沒有要求驗證者集合依公鑰排序；offender 被 Φ 歸零是 §6 的機制，與索引正規化無關。",
  "同一個 epoch 內索引與人的對應是固定的；被懲罰者不會讓索引被別人接手。",
 ],
},
{
 "id": "ch05-offenders-marker-why",
  "alsoCh": ["10", "6"],
 "ch": "5", "section": "5.3 The Markers",
 "gpRef": "eq. 5.11；§10", "difficulty": 2, "kind": "rationale",
 "tags": ["header", "markers", "disputes"],
  "stemZh": "offenders marker 是一串普通的 Ed25519 金鑰、幾乎每一塊都是空的，而且它重複了 disputes 處理本來就會寫進狀態的資訊。為什麼還要放進 header？",
  "optionsZh": [
   "因為懲罰會改變之後哪些金鑰可以簽署，而只讀 header 的追隨者若沒有它，就會持續接受那些鏈上早已排除的 validator 的簽章",
   "因為 disputes extrinsic 是 optional 的、在封存的區塊中可能被裁剪掉，所以這個 marker 是關於「誰在何時被懲罰」的唯一持久鏈上紀錄",
   "因為 offender 必須在其判決生效前一個區塊就被公告，好給被指控者一個在排除定案之前發表反證的窗口",
   "因為 accumulation 階段在改寫 validator 佇列時讀的正是這個 marker，所以少了它，這次懲罰對下個 epoch 的金鑰輪替就會是不可見的"
  ],
  "stem": "The offenders marker is a plain sequence of Ed25519 keys, empty in almost every block, and it duplicates information that disputes processing already puts into state. Why carry it in the header?",
 "options": [
  "Because punishment changes which keys may sign later, and a follower that only reads headers would otherwise keep accepting signatures from validators the chain has already excluded",
  "Because the disputes extrinsic is optional and may be pruned from archived blocks, so the marker is the only durable on-chain record of who was punished and when",
  "Because offenders must be announced one block before their verdicts take effect, giving the accused a window to publish a counter-proof before the exclusion becomes final",
  "Because the marker is what the accumulation stage reads when it rewrites the validator queue, so leaving it out would make the punishment invisible to the next epoch's key rotation",
 ],
 "answer": 0,
 "explanation": "H_O ∈ ⟦ed25519 key⟧ 是一個**可以為空、但永遠不是 ∅** 的普通序列——H_E 與 H_W 才是 optional，這個型別差異本身就是常考點（空序列與「沒有這個欄位」在 JAM 的編碼裡是兩件事）。§10 把它釘死為 H_O ≡ [k | (k,…) ∈ E_C] ⌢ [k | (k,…) ∈ E_F]，也就是本塊 disputes extrinsic 裡culprits 與 faults 兩段的金鑰接起來，「must contain exactly the keys of all new offenders」。**放進 header 的理由跟 epoch marker 同一條線：受眾不同。** 懲罰會改變「之後誰的簽章算數」——被列為 offender 的 validator，其金鑰在下次 epoch 換屆時會被 Φ 整筆歸零（eq. 6.15），從此不能出塊、不能擔保、不能背書。而只讀 header 的輕客戶端不會處理 disputes extrinsic、也不持有狀態裡的 ψ_O（offenders 集合）；沒有這個 marker，它就會繼續接受早該被排除的簽章，等於安全性破口。**所以它不是重複**：狀態裡那份 ψ_O 是給完整節點做狀態轉移用的，header 這份是給只跟著 header 鏈走的人用的，兩者受眾與用途都不同。這也解釋了為什麼它「幾乎每塊都是空的」還是要留著——成本是 1 個位元組的長度前綴，而少了它，輕客戶端就沒有任何管道得知驗證者被剔除。",
 "optNotes": [
  "讓只讀 header 的人知道「誰的簽章不再算數」，正是把 offender 放上 header 的理由。",
  "extrinsic 不會被協定層剪枝，marker 也不是為了保存歷史而存在。",
  "GP 沒有給被指認者緩衝期；verdict 一旦上鏈就生效。",
  "accumulation 讀的是狀態裡的 ψ，不是 header 的 marker。",
 ],
},
{
 "id": "ch05-markers-optionality-cost",
  "alsoCh": ["6", "10"],
 "ch": "5", "section": "5.3 The Markers",
 "gpRef": "eq. 5.11", "difficulty": 2, "kind": "concept",
 "tags": ["header", "markers", "size"],
  "stemZh": "三個 marker 中有兩個是 optional、一個不是。考慮到各自被填入的頻率與可能的大小，這個不對稱買到了什麼？",
  "optionsZh": [
   "那兩個可能很大的——一整套金鑰、以及一整個 epoch 的 ticket——每個 epoch 至多出現一次，所以做成 optional 能讓平常的 header 維持固定的小尺寸；第三個平常是空的，而空序列本來就幾乎不佔空間",
   "做成 optional 的那兩個是驗證者可以合法忽略的，所以信任對等節點的節點可以跳過解碼它們；第三個則必須永遠存在，因為 seal 是對它計算的，欄位缺席會改變被簽署的訊息",
   "這個不對稱反映的是哪些欄位由 Safrole 產生、哪些由 disputes 產生：Safrole 產出的一切都是 optional，因為 ticket 競賽可能失敗；而 disputes 的產出是必要的，因為 verdict 不可能無法作結",
   "它讓編碼器能區分「沒有發生 epoch 變更」與「發生了 epoch 變更但金鑰集合是空的」，而這個區別在 genesis 以及集合大小變成零位 validator 之後很重要"
  ],
  "stem": "Two of the three markers are optional and one is not. What does that asymmetry buy, given how often each is populated and how large each can get?",
 "options": [
  "The two that can be large — a full key set and a whole epoch of tickets — appear at most once per epoch, so making them optional keeps the ordinary header to a fixed small size; the third is normally empty and an empty sequence already costs almost nothing",
  "The two that are optional are the ones a verifier may legitimately ignore, so a node that trusts its peers can skip decoding them; the third must always be present because the seal is computed over it and a missing field would change the signed message",
  "The asymmetry mirrors which fields are produced by Safrole and which by disputes: everything Safrole emits is optional because the ticket contest may fail, while disputes output is mandatory because a verdict cannot fail to conclude",
  "It lets the encoder distinguish 'no epoch change happened' from 'an epoch change happened with an empty key set', a distinction that matters at genesis and after a set-size change to zero validators",
 ],
 "answer": 0,
 "explanation": "**先把型別記號對齊**：`?S`（GP 的 optional）是「S ∪ {∅}」，序列化時前面掛一個判別位元組；`⟦T⟧` 是元素型別 T 的序列，`⟦T⟧_n` 是長度固定 n 的序列。eq. 5.11：H_E ∈ ?(H, H, ⟦(bskey, edkey)⟧_V)、H_W ∈ ?(⟦ticket⟧_E)、H_O ∈ ⟦ed25519 key⟧——**前兩個是 optional，第三個只是一般序列**。再看 App. C 的三個編碼器：E(0) = [0]（一般自然數編碼，0 就是單一位元組）；maybe(x) 在 x = ∅ 時是 0、否則是 (1, x)；var(x) ≡ (|x|, x)，E(var(x)) = E(|x|) ⌢ E(x)。代進去：H_E 不存在是 E_epochmark(∅) = E(0) = 1 byte、H_W 不存在是 maybe(∅) = 1 byte、H_O 為空是長度前綴 E(0) 後面接空 = 1 byte——**三者在空的時候都恰好一個位元組**，沒有誰更省。所以 optional 買到的不是「空的時候更便宜」，而是應付有內容時的極端落差。前兩個一旦出現就很大——一整套 validator 金鑰、或整個 epoch 的 600 張 ticket——但每個 epoch 至多出現一次，所以做成 optional——用那 1 byte 的判別位元組把「有」與「無」兩種形狀切開，平時的 header 就維持固定的小尺寸。第三個沒有這種兩極分布，而且它是序列——**長度前綴本身已經兼任判別子**，再包一層 optional 只會多一個判別位元組，還會生出 ∅ 與 [] 兩種都表示「沒有 offender」的寫法，語意重複。這是「編碼形狀跟隨出現頻率與大小」的取捨，也是最容易被追問「為什麼 H_O 不是 optional」的地方。順帶澄清一個常見誤解：**H_O 是可以為空的，絕大多數區塊都是空的**。§10 定義 H_O ≡ [k | (k,…) ∈ E_C] ⌢ [k | (k,…) ∈ E_F]（E_C 是 culprits、E_F 是 faults，都是 disputes extrinsic E_D 的成分），「must contain exactly the keys of all new offenders」——沒有新的 offender 就是空序列。它的強制性不在「非空」，而在「必須與本塊 E_D 帶進來的 culprits 與 faults 逐項相符」：有新 offender 卻留空、或列出沒有依據的鍵，都會讓區塊無效。另外 H_E 的金鑰序列恆為 V 筆（整個 γ′_P），同樣不會是空的。",
 "optNotes": [
  "大而罕見的用 optional、小而常在的用空序列，正是這組型別差異的成本考量。",
  "seal 涵蓋的是 E_U 的全部欄位，三個 marker 都在裡面，沒有哪個因為 optional 而被排除。",
  "H_W 確實與 Safrole 有關，但 H_E 也在 epoch 邊界必然出現，不是「可能失敗」才有。",
  "epoch marker 的金鑰序列恆為 V 筆（整個 γ′_P），根本不存在「空金鑰集」這個狀態可供區分。",
 ],
},
{
 "id": "ch05-marker-misplacement",
 "ch": "5", "section": "5.3 The Markers",
 "gpRef": "§5.3；§6.6", "difficulty": 3, "kind": "concept",
 "tags": ["header", "markers", "validity"],
  "stemZh": "一個區塊在 epoch 中途抵達，卻帶著已填入內容的 epoch marker。validator 該怎麼處理它？這個處理背後的通則又是什麼？",
  "optionsZh": [
   "拒絕該區塊：marker 不是可以自由填寫的註記，而是由狀態轉移本身決定的值，所以一個 marker 與轉移產出不一致的 header，根本就不是一個有效的 header",
   "接受該區塊但忽略那個 marker，因為 marker 是給輕客戶端的輔助資訊，全節點會自己從狀態導出同樣的資訊；只有當某個 marker 以影響 seal 的方式與狀態相牴觸時才會使區塊無效",
   "接受該區塊並採納那個 marker，把它當成對接下來 epoch 的提前公告；這正是出塊者得以預先發布一個狀態尚未套用之集合變更的機制",
   "只有當該 marker 的金鑰集合與狀態裡已有的不同時才拒絕；一個僅僅出現在非預期時間點的 marker 是無害的，因為它的內容仍然正確"
  ],
  "stem": "A block arrives mid-epoch carrying a populated epoch marker. How should a validator treat it, and what is the general principle behind that treatment?",
 "options": [
  "Reject the block: the markers are not free-form annotations but values the state transition itself determines, so a header whose marker disagrees with what the transition produces is simply not a valid header",
  "Accept the block but ignore the marker, since markers are advisory aids for light clients and a full node derives the same information from state; only a marker that contradicts state in a way affecting the seal can invalidate a block",
  "Accept the block and adopt the marker, treating it as an early announcement of the coming epoch; this is the mechanism by which an author can pre-publish a set change that the state has not yet applied",
  "Reject the block only if the marker's key set differs from the one already in state; a marker that merely appears at an unexpected time is harmless because its content is still correct",
 ],
 "answer": 0,
 "explanation": "marker 不是出塊者可以自由填寫的註記欄位：H_E 與 H_W 的**內容**與**出現時機**都由狀態轉移決定。eq. 6.28 把 H_E 定義成一個依 e′ > e 分支的式子——是新 epoch 的第一塊就必須帶（且內容必須等於 η′_0、η′_1 與 γ′_P 的金鑰），不是就必須是 ∅；eq. 6.29 對 H_W 同理（條件是 e′ = e ∧ m < Y ≤ m′ ∧ |γ_A| = E）。所以「epoch 中間出現 epoch marker」不是一個可以容忍的瑕疵，而是 **header 與狀態轉移不一致**——區塊無效，團隊的 fuzzer 把這類錯誤報成 InvalidEpochMark / InvalidTicketsMark（issue #770）。**背後的通則值得記牢，口試常從這裡追問**：header 裡每一個欄位都是對狀態轉移結果的**承諾**，不是附註。驗證一個區塊，本質上就是重跑轉移、再確認每個承諾都對得上——H_R 對得上父的 posterior root、H_X 對得上實際的 extrinsic、marker 對得上 Safrole 與 disputes 算出來的值。這也回答了一個常見的追問：marker 明明是為輕客戶端設計的，為什麼全節點還要檢查它？因為全節點若不檢查，就等於讓出塊者能對輕客戶端說謊而不受懲罰——marker 的可信度完全建立在全節點會驗證它。",
 "optNotes": [
  "marker 由狀態轉移決定，不一致即無效，這是 header 欄位的一般原則。",
  "把 marker 當成可忽略的註記，等於允許出塊者對輕客戶端說謊而不受懲罰。",
  "GP 沒有「預先公告」的機制；epoch 邊界由 τ 與 E 決定，不由出塊者宣告。",
  "出現時機本身就是規格的一部分，內容正確不能補救時機錯誤。",
 ],
 "trap": "面試常追問「如果出塊者亂填 marker 會怎樣」——答「無效」還不夠，要說出「marker 是轉移的承諾」這條通則。",
},
{
 "id": "ch05-absent-commitments",
 "ch": "5", "section": "5.1 The Header",
 "gpRef": "eq. 5.1；§4", "difficulty": 3, "kind": "rationale",
 "tags": ["header", "design", "comparison"],
  "stemZh": "Ethereum 的 header 承諾了執行後的狀態、一個 receipts root、以及消耗掉的 gas。JAM 的 header 三者皆無。這三個角色分別跑到哪裡去了？",
  "optionsZh": [
   "執行後的狀態以下一個區塊的先前 state root 之姿出現；逐項的結果住在 report 內部的 work-digest 裡而不在 header；而資源用量是靠 core time 與 gas 上限事先設限，而不是事後回報",
   "三者都被摺進 extrinsic 雜湊，它的五個成分裡包含一個 results 成分；JAM 只是把同樣的承諾重新組織到單一欄位底下，好讓輕客戶端只需跟隨一個 root 而不是三個",
   "執行後的狀態由 seal 承諾，因為它簽署了出塊者算出的 state root；receipt 被 header 裡的 accumulation output log 取代；而 gas 被省略是因為 JAM 是以時槽而非以 gas 計量 core time",
   "三者都被延後到 BEEFY 的承諾，這也是 JAM 的 header 比較小的原因：任何外部驗證者需要的東西都是對著 accumulation-output MMR 證明的，而不是對著 header 本身"
  ],
  "stem": "An Ethereum header commits to the post-state, a receipts root and the gas consumed. A JAM header carries none of the three. Where does each of those roles go instead?",
 "options": [
  "The post-state appears as the next block's prior state root; per-item outcomes live in work-digests inside reports rather than in the header; and resource use is bounded in advance by core time and gas ceilings instead of being reported after the fact",
  "All three are folded into the extrinsic hash, whose five components include a results component; JAM simply reorganizes the same commitments under one field so that light clients need to follow only one root rather than three",
  "The post-state is committed to by the seal, which signs the state root the author computed; receipts are replaced by the accumulation output log in the header; and gas is omitted because JAM meters core time in slots rather than in gas",
  "They are all deferred to the BEEFY commitment, which is why a JAM header is smaller: anything an external verifier needs is proven against the accumulation-output MMR rather than against the header itself",
 ],
 "answer": 0,
 "explanation": "三件 Ethereum header 有、JAM 沒有的東西，各自的去處不同。**post-state root → 下一塊的 H_R**：JAM 的 header 帶的是 **prior** state root，某一塊的執行結果要到**下一塊**才被承諾。為的是讓出塊與 Merklization 管線化——出塊者不必算完整棵 trie 才能發布。代價是 β_H 最新一筆的 state root 先填零，由下一塊的 β† 補正（eq. 7.5）。**receipts root → work-report 裡的 digest**：JAM 根本沒有 receipt 這一層。每個 work-item 的結果（成功的 blob，或 𝔼 = {∞, ☇, BADEXPORTS, ⊖, BAD, BIG} 裡的錯誤值）留在 work-report 的 digest 中隨報告上鏈，accumulate 直接讀得到。**gas used → 事前設限而非事後回報**：JAM 不回報用量，而是預先卡住上限——core time 本身就是稀缺資源、單份 report 有 G_A = 10^7 的上限、整塊有 G_T、PVM 則以 basic block 為單位預先扣款，超過就是 OOG。**通則**：Ethereum 的三個欄位都是「執行完之後才知道的事實」，而 JAM 刻意讓 header 只承諾「發布當下就已確定的東西」——這正是它能維持十個欄位、大小固定的原因，也是 pipelining 得以成立的前提。",
 "optNotes": [
  "prior state root、digest 裡的結果、事前設限取代事後回報，三者各自對應原本的角色。",
  "extrinsic hash 承諾的是輸入（extrinsic），不是執行結果；它沒有 results 分量。",
  "seal 簽的是 header 自身（不含 seal 的編碼），不是狀態根；header 也沒有 accumulation output log 欄位。",
  "BEEFY 的 MMR 承諾 accumulation output，取代不了 state root 與逐項結果。",
 ],
},
]
