# -*- coding: utf-8 -*-
"""「新舊對照」分頁：Polkadot 1.0 → 2.0 → JAM 的宏觀設計演進。

每一列都標來源代碼（見最後一節）。JAM 欄以 Gray Paper 0.8.0 為準；
Polkadot 欄以 Polkadot Wiki 與 Polkadot SDK 文件為準。標「我的對照」的是整理者的推論。
文字走 inlineCode()：支援 `code` 與 **粗體**，不支援其他 markdown。
"""

PAGE = {
 "id": "polkadot-evolution",
 "title": "Polkadot 1.0 → 2.0 → JAM：設計怎麼演進",
 "lead": "安全賽局三代都是同一套（ELVES）。差別在三件事：core 上能跑什麼、怎麼拿到 core、算完的結果怎麼進 state。"
         "每一列都標了來源；JAM 欄以 Gray Paper 0.8.0 為準。",
 "checked": "2026-10-04",
 "sections": [

  {"id": "gist", "title": "一句話", "blocks": [
    {"kind": "list", "items": [
      "**Polkadot 1.0**：Relay Chain 加上一群 parachain。core 只做一件事——驗某條 parachain 的 block；要用 core，得先做出一條鏈，再用拍賣租到 slot。",
      "**Polkadot 2.0**：同一個架構上的三項升級：asynchronous backing、Agile Coretime、elastic scaling。不是一條新鏈，也沒有換訊息傳輸協定。",
      "**JAM**：把 Relay Chain 的 base protocol 換掉。core 變成通用的運算單位，跑任何 service 的 `refine`，結果由鏈上的 `accumulate` 寫進同一個 σ；parachain 變成 JAM 上的一個 service。",
    ]},
    {"kind": "callout", "text": "最短的記法：1.0 賣「一條有共享安全的鏈」；2.0 讓這條鏈買 core 更有彈性；JAM 賣「一段有共享安全的 CPU 時間」。"},
  ]},

  {"id": "table", "title": "三代對照", "blocks": [
    {"kind": "table", "wide": True,
     "head": ["面向", "Polkadot 1.0", "Polkadot 2.0", "JAM（GP 0.8.0）", "來源"],
     "rows": [
      ["基本單位",
       "parachain：一整條鏈，自己的 runtime 與 state",
       "同左（wiki 現在多稱 rollup）",
       "service：code + storage + balance，入口是 `refine` 與 `accumulate`",
       "W1 · GP §4.9、§9"],
      ["core 上跑什麼",
       "那條 parachain 的驗證函數（PVF），吃 collator 給的 PoV",
       "同左",
       "任何 service 的 `refine`；先過該 core 的 authorizer（`is-authorized`）",
       "W-PP · GP §8、§14"],
      ["怎麼拿到 core",
       "slot auction：以 3 個月為一段、最長兩年，要鎖 DOT 或辦 crowdloan",
       "Agile Coretime：bulk（一期 28 天）或 on-demand，在 Coretime Chain 購買，可切割、可交錯",
       "買 coretime → assigner 把你的 authorizer 排進 φ[c] → 每個 block 移一格進 α[c]。怎麼賣，GP 明說不在範圍內",
       "W1 · W-AC · GP §4.9、§8"],
      ["一個單位用幾個 core",
       "一條 parachain 固定一個",
       "elastic scaling：同一條 rollup 可同時用多個",
       "沒有綁定：core 只認 α[c] 裡的 authorizer，同一個 service 的 work-package 可以同時在多個 core 上",
       "W2 · W-ES · GP §8"],
      ["節奏",
       "parachain 每 12 秒一塊，每塊執行上限 0.5 秒",
       "asynchronous backing：每 6 秒一塊，執行上限 2 秒",
       "slot 6 秒；每個 core 每個 block 至多收一份 work-report；`refine` 的 gas 上限 5×10⁹，`accumulate` 每份 report 10⁷",
       "W1 · W-AB · GP App. I"],
      ["core 的輸出",
       "candidate；被 included 之後，那個 block 就算是 parachain 的一部分",
       "同左",
       "work-report（不定長部分上限 48 KiB）；available 之後，由鏈上的 `accumulate` 決定怎麼寫進 state",
       "SDK · GP §11、§12"],
      ["state",
       "relay chain 一份，加上每條 parachain 各自一份",
       "同左",
       "單一 σ；所有 service 的 account 都在 δ 裡",
       "GP §2.1、§4.2"],
      ["單位之間怎麼互動",
       "XCM 訊息；parachain 之間走 HRMP，完整訊息存進 relay chain",
       "同左——XCMP 仍未完成",
       "原生：`accumulate` 裡的 deferred transfer（帶 memo 與 gas）、`refine` 之間的 segment import／export。相容層：parachains service 內走 full XCMP",
       "W-XT · GP §12、§14 · W-JAM"],
      ["出塊",
       "BABE：每個 slot 各自 VRF 抽籤，可能多人中，也可能沒人中（另有 secondary 機制補）",
       "同左",
       "Safrole：ticket 提前一個 epoch 匿名排定，一個 slot 一位 author",
       "W-C · GP §4.8、§6"],
      ["finality 與橋接",
       "GRANDPA；BEEFY 給橋用",
       "同左",
       "GRANDPA 與 BEEFY 都保留；best-chain 規則多了「block 必須已 audited」",
       "W-C · GP §17–19"],
      ["安全賽局",
       "ELVES：backing → availability → approval checking → disputes",
       "同左",
       "同一套賽局、換了名字：guaranteeing → assuring → auditing → judging",
       "W1 · SDK · GP §2.1、§4.9.1"],
      ["VM",
       "Wasm",
       "同左",
       "PVM：以 RISC-V RV64EM 為基礎，13 個 64-bit register",
       "D · GP §4.7、App. A"],
      ["使用者交易",
       "有：relay chain 與各 parachain 都收簽名交易",
       "有；常用功能逐步移到 system chain，讓 relay chain 的 blockspace 留給驗證 parachain",
       "沒有交易：block 只有五種 extrinsic（tickets、preimages、guarantees、assurances、disputes）；使用者的東西走 work-package",
       "W-SC · GP §4.1、§4.9"],
      ["鏈本身管多少",
       "relay chain 內建 staking、governance、balances、identity、treasury",
       "逐步搬到 system chains：Asset Hub（balances、transfers、staking）、People、Coretime、Collectives、Bridge Hub",
       "base protocol 不含這些：staking、coretime 銷售、governance 都做成 service",
       "W1 · W-SC · GP §4.8、§4.9 · W-JAM"],
      ["協定怎麼升級",
       "relay chain 的 runtime 可以升級",
       "同左",
       "wiki：JAM 的 base protocol 設計成不可升級，可升級性移到 service；JAM 本身以一次整體升級導入",
       "W-JAM"],
      ["既有的 parachain",
       "系統的主體",
       "同左",
       "由 JAM 上的 parachains service 承接（wiki 的說法是整併 Polkadot 1.1 的功能）",
       "W-JAM · GP §4.9"],
     ]},
  ]},

  {"id": "v2", "title": "Polkadot 2.0 的三項升級", "blocks": [
    {"kind": "p", "text": "wiki 把 Polkadot 2.0 定義成三項技術升級。三項都在改「parachain 怎麼取得、怎麼使用 core」，沒有一項是換訊息傳輸協定。"},
    {"kind": "table",
     "head": ["升級", "改了什麼", "wiki 給的數字", "JAM 裡對應的想法"],
     "rows": [
      ["Asynchronous backing",
       "collator 可以蓋在還沒被 relay chain 收進去的祖先上（unincluded segment），relay parent 不必是最新一塊；parablock N+1 的 backing 和 N 的 inclusion 可以落在同一個 relay block",
       "parachain block 12 秒 → 6 秒；每塊執行 0.5 秒 → 2 秒",
       "同一種 pipelining 寫進協定本身：report 的 anchor 可以是最近 8 個 block 之一（β），header 承諾 prior state root，出塊不必等 Merklize"],
      ["Agile Coretime",
       "取代 slot auction。coretime 變成可切割（split）、可交錯（interlace）、可續約的 region，在 Coretime Chain 的 broker pallet 購買；分 bulk 與 on-demand",
       "bulk 一期 28 天（5,040 個 timeslice）",
       "GP §4.9 直接說 JAM 的 coretime 是以 Polkadot 的 Agile Coretime 為基礎。買賣不在 GP 範圍；買到之後落到鏈上的動作，是 assigner 呼叫 `assign` 寫 φ[c]"],
      ["Elastic scaling",
       "同一條 rollup 同時用多個 core，在同一個 relay block 裡收進多個 parablock。依賴前兩項；wiki 稱它是 2.0 的最後一項技術升級",
       "wiki 的例子：兩個 core 讓四個 parablock 的 inclusion 從 24 秒降到 12 秒",
       "JAM 本來就沒有「一個 service 一個 core」：α[c] 放行誰，誰的 work-package 就能上那個 core"],
     ]},
    {"kind": "callout", "text": "第四欄是我做的對照，不是官方說法；只有 Agile Coretime 那一格有 GP 原文依據。"},
  ]},

  {"id": "terms", "title": "名詞對照", "blocks": [
    {"kind": "p", "text": "安全賽局是同一套，所以名詞幾乎一對一。口試時兩邊的說法都可能出現。"},
    {"kind": "table",
     "head": ["Polkadot", "JAM", "差在哪"],
     "rows": [
      ["collator", "builder", "都在鏈下組輸入；GP 不規範 builder 是誰"],
      ["PoV（proof of validity）", "work-package／bundle", "PoV 是一條鏈的 block 加見證；work-package 可以裝 1–16 個 work-item，各屬不同 service"],
      ["PVF（validation function）", "`is-authorized` + `refine`", "PVF 回答「這個 block 合法嗎」；`refine` 可以是任何運算，輸出交給 `accumulate`"],
      ["backing（backing group）", "guaranteeing（每個 core 三位 guarantor）", "Polkadot：backing group 過半數簽名即可上鏈；JAM：三位 guarantor 至少兩位簽名"],
      ["candidate receipt", "work-report", "candidate 被 included 就結束了；report 帶的 digest 還要經過 `accumulate`"],
      ["availability bitfield", "assurance", "都是「我拿到我那片了」；兩邊的門檻都是超過三分之二的 validator"],
      ["approval checking（secondary checker）", "auditing（auditor）", "都是用 VRF 抽人重跑"],
      ["dispute", "judgment → verdict（E_D）", "Polkadot 的 dispute 會觸發 slash；JAM 鏈上只記 offender，懲罰交給上層的 service"],
      ["parachain", "service", "不是一比一：既有的 parachain 是住在 parachains service 裡面"],
      ["relay chain", "JAM chain", "JAM 的 base protocol 不含 staking、governance、balances"],
      ["slot lease／coretime region", "α[c] 裡的 authorizer", "JAM 鏈上只看得到 authorizer，看不到買賣"],
     ]},
  ]},

  {"id": "scale", "title": "規模：GP 自己的比較", "blocks": [
    {"kind": "p", "text": "GP §20 給了一組它自己的估算。口試被問「JAM 比 Polkadot 強多少」時，引這組最安全。"},
    {"kind": "table",
     "head": ["", "Polkadot（GP 的說法）", "JAM"],
     "rows": [
      ["同時驗證", "最多約 80 條 parachain", "341 個 core，每個 slot 處理 341 份 work-package"],
      ["運算量", "每條每 6 秒做 1 秒原生運算，合計約 13 倍單核原生 CPU", "約 85 倍單核原生 CPU"],
      ["資料可得性", "約 67 MB/s", "約 682 MB/s"],
      ["accumulation", "沒有這個能力，GP 說無法比較", "每份結果約 10 ms，可完整讀寫 chain state"],
      ["取用門檻", "拍賣 slot，GP 寫作時約 50 個（§2.1）", "買 coretime，無許可"],
     ]},
    {"kind": "list", "items": [
      "§4.9.1 說 in-core 可達「300 倍以上」，§20 說「約 85 倍」。兩個數字的基準不同：前者相對於一台全速跑 VM 的機器，後者相對於原生 CPU 的單核；GP 假設一個 core 以原生 25–50% 的速度執行，341 × 0.25 ≈ 85。這個換算是我的讀法，GP 沒有把兩個數字並列說明。",
      "這些都是 GP 的模型估算，不是實測。",
    ]},
  ]},

  {"id": "xcm", "title": "訊息怎麼傳：三層不要混", "blocks": [
    {"kind": "list", "items": [
      "**語言**：XCM。描述「要對方的 consensus system 做什麼」，由 XCVM 執行。它不規定訊息怎麼送。",
      "**運送**：UMP、DMP（合稱 VMP）、HRMP、XCMP。把 XCM 訊息搬到目的地的管道。",
      "**JAM 原生互動**：service 在 `accumulate` 裡發 deferred transfer（金額、memo、gas），收款的 service 在下一輪被叫起來處理。它不是 XCM 的新版本，也不需要包成 XCM。",
    ]},
    {"kind": "table",
     "head": ["Transport", "方向", "資料走哪裡", "狀態"],
     "rows": [
      ["UMP", "parachain → relay chain", "經 relay chain", "使用中"],
      ["DMP", "relay chain → parachain", "經 relay chain", "使用中"],
      ["HRMP", "parachain → parachain", "完整訊息存進 relay chain 的 storage", "使用中。定位是 stop-gap（又稱 XCMP-lite），XCMP 完成後預定淘汰"],
      ["XCMP", "parachain → parachain", "本文不經 relay chain；鏈上只放 header", "開發中，wiki 標明尚未完整實作"],
     ]},
    {"kind": "table",
     "head": ["", "Polkadot 1.0", "Polkadot 2.0", "JAM"],
     "rows": [
      ["XCM（語言）", "使用", "使用", "在 parachains service 內延續"],
      ["parachain ↔ parachain", "HRMP", "HRMP——2.0 的三項升級不含換 transport", "wiki：JAM 強制 full XCMP"],
      ["parachain ↔ relay chain", "VMP（UMP + DMP）", "同左", "JAM 沒有同樣的拓撲；相容行為收在 parachains service 裡"],
      ["原生單位之間", "—", "—", "deferred transfer + memo（GP §12）"],
      ["Accords", "—", "—", "wiki 有描述（跨 parachain 的共享邏輯、可同步互動），沒給實作狀態"],
     ]},
    {"kind": "p", "text": "**JAM 為什麼非 full XCMP 不可。** wiki 的理由：HRMP 的訊息全部走鏈上，payload 會被壓到 4 kB 以下；XCMP 只把 header 放鏈上，本文在鏈下傳。對回 GP：`refine` 能交給 `accumulate` 的東西就是 work-report，不定長部分上限 48 KiB，訊息本文不可能跟著上鏈。後半句是我的對照。"},
  ]},

  {"id": "replaced", "title": "哪些真的被取代", "blocks": [
    {"kind": "table",
     "head": ["舊", "新", "範圍與狀態"],
     "rows": [
      ["slot auction／lease", "Agile Coretime", "Polkadot 2.0。跟訊息傳輸無關"],
      ["同步 backing（12 秒一塊）", "asynchronous backing（6 秒一塊）", "Polkadot 2.0"],
      ["HRMP", "XCMP", "目標替換。wiki 仍標 XCMP 未完成，不能說已經換完"],
      ["Relay Chain 的 base protocol", "JAM", "未來的一次整體升級"],
      ["relay chain 內建的 parachain 邏輯", "JAM 上的 parachains service", "功能由 service 承接，不再寫死在 base protocol"],
      ["BABE", "Safrole", "JAM。GP 說 Safrole 是 Sassafras 的簡化版"],
      ["Wasm", "PVM", "JAM"],
      ["relay chain 上的 staking、governance、balances", "system chain，之後是 JAM 上的 service", "2.0 時期已經在搬；JAM 把它變成原則"],
     ]},
    {"kind": "p", "text": "**不要這樣說：**"},
    {"kind": "list", "items": [
      "「Polkadot 2.0 用 XCMP 取代了 HRMP」——2.0 的三項升級裡沒有這一項。",
      "「XCMP 取代 XCM」——一個是運送，一個是語言。",
      "「XCMP 取代 UMP／DMP」——方向不同。",
      "「JAM 的 deferred transfer 取代了 XCM」——那是 JAM 原生 service 的機制；parachain 之間仍是 XCM 走 XCMP。",
      "「Accords 已經取代 XCM」——還只是設計方向。",
      "「JAM 把 parachain 拿掉了」——parachain 由 parachains service 繼續跑。",
      "「JAM 換了安全模型」——還是 ELVES，GP §2.1 自己說的。",
    ]},
  ]},

  {"id": "audit", "title": "查證備註", "blocks": [
    {"kind": "p", "text": "這一頁逐條對過來源。查的時候發現幾處出入，記在這裡。"},
    {"kind": "list", "items": [
      "**wiki 的 JAM 頁有些數字落後 GP 0.8.0。** wiki 寫 `refine` 的輸出上限 90 kB、輸入 15 MB，並把 OnTransfer 列為第三個入口。GP 0.8.0 是 W_R = 48 KiB、W_B = 13,791,360 octet，而 `on_transfer` 從 0.7.1 起已併入 `accumulate`。本頁的 JAM 欄一律用 GP。",
      "**wiki 的 parachains protocol 頁，在 availability 那一步寫的是「⅓ + 1 位 validator 回報持有」。** Polkadot SDK 的 implementers' guide（runtime 的 inclusion 模組）寫的是超過 2/3 的 bitfield 才算 available；⅓ 是重建資料所需的比例。本頁採後者。",
      "**wiki 的 Polkadot 2.0 頁沒有提 XCMP、HRMP 或 JAM。**「2.0 沒換 transport」是由 2.0 頁的範圍，加上 XCM transport 頁寫的現況推得的。",
      "**system chain 的搬遷沒有日期。** wiki 的 system chains 頁用現在式描述 Asset Hub 管 balances、transfers、staking，但沒寫何時搬的，也沒逐項列出 relay chain 還剩什麼。",
      "**wiki 說 parachains service 整併的是「Polkadot 1.1」的功能**，不是寫 1.0 或 2.0。",
      "**三處是整理者的推論**，來源沒有直接這樣寫：2.0 三項升級與 JAM 的對照欄、85 倍與 300 倍的換算、W_R 與 full XCMP 的關係。頁面上都有標。",
    ]},
  ]},

  {"id": "sources", "title": "來源", "blocks": [
    {"kind": "p", "text": "表格「來源」欄的代碼對應如下。"},
    {"kind": "links", "items": [
      {"code": "GP",    "label": "Gray Paper 0.8.0（本 repo 釘在 commit 07f041d）", "url": "https://graypaper.com/"},
      {"code": "W1",    "label": "Polkadot Wiki — Polkadot 1.0", "url": "https://wiki.polkadot.com/general/polkadot-v1/"},
      {"code": "W2",    "label": "Polkadot Wiki — Polkadot 2.0", "url": "https://wiki.polkadot.com/general/polkadot-v2/"},
      {"code": "W-AB",  "label": "Polkadot Wiki — Asynchronous Backing", "url": "https://wiki.polkadot.com/learn/learn-async-backing/"},
      {"code": "W-AC",  "label": "Polkadot Wiki — Agile Coretime", "url": "https://wiki.polkadot.com/learn/learn-agile-coretime/"},
      {"code": "W-ES",  "label": "Polkadot Wiki — Elastic Scaling", "url": "https://wiki.polkadot.com/learn/learn-elastic-scaling/"},
      {"code": "W-XT",  "label": "Polkadot Wiki — XCM Transport", "url": "https://wiki.polkadot.com/learn/learn-xcm-transport/"},
      {"code": "W-C",   "label": "Polkadot Wiki — Consensus", "url": "https://wiki.polkadot.com/learn/learn-consensus/"},
      {"code": "W-PP",  "label": "Polkadot Wiki — Parachains Protocol", "url": "https://wiki.polkadot.com/learn/learn-parachains-protocol/"},
      {"code": "W-SC",  "label": "Polkadot Wiki — System Chains", "url": "https://wiki.polkadot.com/learn/learn-system-chains/"},
      {"code": "W-JAM", "label": "Polkadot Wiki — JAM Chain", "url": "https://wiki.polkadot.com/learn/learn-jam-chain/"},
      {"code": "SDK",   "label": "Polkadot SDK implementers' guide — Protocol Overview", "url": "https://paritytech.github.io/polkadot-sdk/book/protocol-overview.html"},
      {"code": "SDK",   "label": "Polkadot SDK implementers' guide — Inclusion", "url": "https://paritytech.github.io/polkadot-sdk/book/runtime/inclusion.html"},
      {"code": "SDK",   "label": "Polkadot SDK — XCM Glossary", "url": "https://paritytech.github.io/polkadot-sdk/master/xcm_docs/glossary/"},
      {"code": "D",     "label": "Kian Paimani — Demystifying JAM", "url": "https://blog.kianenigma.com/posts/tech/demystifying-jam/"},
    ]},
  ]},
 ],
}
