# -*- coding: utf-8 -*-
# Glossary — state components, block & extrinsic (GP 0.8.0 symbols verified against gp-src/preamble.tex)
TERMS = [
{"sym":"σ","term":"state","zh":"整體狀態","cat":"state","gpRef":"eq. 4.4",
 "one":"JAM 的完整狀態，拆成 17 個大致獨立的元件。",
 "body":"σ ≡ (α, β, θ, γ, δ, η, ι, κ, λ, ρ, τ, φ, χ, ψ, π, ω, ξ)。拆成獨立元件有兩個目的：一是讓 state-transition 的依賴圖夠淺、可以平行計算（§4.2.1）；二是讓 Merklization 的 key 空間可以用單一 byte 的 chapter 前綴分區（附錄 D 的 C(i)）。σ′ 代表 posterior（本區塊處理完之後）的狀態。",
 "rel":["σ′","C(i)","STF"]},
{"sym":"α","term":"authorizer pool","zh":"授權池","cat":"state","gpRef":"eq. 8.1–8.3",
 "one":"每個 core 目前可用的 authorizer hash 序列（最多 O = 8 個）。",
 "body":"α ∈ [[H]_{:O}]_C。guarantee 上鏈時檢查 w_a ∈ α[w_c]（用 **prior** α）。每個區塊每個 core 都會從 queue 補一個進來：α′[c] = ←(F(c) ⌢ φ′[c][H_T mod Q])^O，其中 F(c) 會把本塊用掉的 authorizer 從**最左邊**移除一個（seqminusl，不是移除全部）。因為要用 posterior 的 φ′，這一步必須排在 accumulation 之後。",
 "rel":["φ","authorizer","O","Q"]},
{"sym":"β","term":"recent history","zh":"近期歷史","cat":"state","gpRef":"eq. 7.1–7.8",
 "one":"最近 H = 8 個區塊的摘要（β_H）加上 accumulation output 的 MMR（β_B）。",
 "body":"β ≡ (β_H, β_B)。β_H 每筆是 (header hash, state root, accumulation-output super-peak, timeslot, 本塊回報的 package hash → segment root)。用途：擋掉重複或過期的 work-report——guarantee 的 anchor 必須對上 β† 的某一筆，package hash 不得出現在 β 的任何一筆裡。β_B 是 Keccak MMR，接收每塊的 accumulation output root。",
 "rel":["β†","β_B","anchor","H (常數)"]},
{"sym":"β†","term":"beta dagger","zh":"補正後的近期歷史","cat":"state","gpRef":"eq. 7.5",
 "one":"把 β_H 最後一筆的 state root 用本塊的 H_R 補上之後的中間值。",
 "body":"因為 header 帶的是 **prior** state root，寫入 β 的當下還不知道自己的 posterior root，所以先填零 hash；下一個區塊一開始就用自己的 H_R 覆蓋回去（β† ≡ β_H except β†[|β_H|−1]_s = H_R）。之後 guarantee 的 anchor 檢查比對的是 β†，不是 β。",
 "rel":["β","H_R","pipelining"]},
{"sym":"γ","term":"Safrole state","zh":"Safrole 狀態","cat":"state","gpRef":"eq. 6.3–6.5",
 "one":"出塊抽籤相關的四元組 (γ_P, γ_Z, γ_S, γ_A)。",
 "body":"γ_P 下個 epoch 的 pending validator keys（每個 epoch 開頭從 ι 重置）；γ_Z 由 γ_P 的 Bandersnatch key 組成的 ring root，用來驗 ticket 的 ring proof；γ_S 本 epoch 的 slot-sealer 序列（E 張 ticket 或 fallback 的 E 把 key）；γ_A ticket accumulator，收集下個 epoch 要用的 ticket（最多 E 筆，留最低的 E 個 id）。",
 "rel":["γ_S","γ_A","γ_Z","ι","κ"]},
{"sym":"γ_S","term":"slot-sealer sequence","zh":"時槽封印序列","cat":"state","gpRef":"eq. 6.25–6.27",
 "one":"本 epoch 每個 slot 由誰出塊：600 張 ticket，或 fallback 的 600 把公鑰。",
 "body":"三種情況（eq. 6.25）：e′ = e + 1 ∧ m ≥ Y ∧ |γ_A| = E → Z(γ_A)（outside-in 排序的 ticket）；e′ = e → 不變；其餘（跳過 epoch、accumulator 未滿、比賽未結束）→ F(η′_2, κ′) 的 fallback key。出塊者用 γ_S[H_T mod E] 對應的私鑰簽 seal。",
 "rel":["γ_A","Z","F","seal","T (ticketed)"]},
{"sym":"γ_A","term":"ticket accumulator","zh":"票券累積器","cat":"state","gpRef":"eq. 6.35",
 "one":"本 epoch 收集到的 ticket，供下個 epoch 排序使用。",
 "body":"γ′_A = 把新 ticket 與舊 accumulator 依 id 排序後取**最低**的 E 個（→^E）。epoch 換屆時歸零重收。提交的 ticket 必須全部留在 γ′_A 裡（否則 extrinsic 無效），且 id 不得與既有的重複。id 越小越好——這是「score」的意思。",
 "rel":["γ_S","ticket","E (常數)","Y"]},
{"sym":"δ","term":"service accounts","zh":"服務帳戶","cat":"state","gpRef":"eq. 9.1–9.3",
 "one":"從 service index 到 service account 的字典，JAM 版的「所有帳戶」。",
 "body":"δ ∈ D⟨N_S → A⟩。每個 account 有 storage、preimages、requests、gratis、code hash、balance、兩個最低 gas、created/lastacc/parent。沒有 nonce（沒有交易就沒有重放問題）。中間狀態：δ† accumulation 之後、δ‡ 更新 lastacc 之後、δ′ 整合 preimage 之後。",
 "rel":["δ†","δ‡","service","a_t"]},
{"sym":"η","term":"entropy pool","zh":"熵累積器","cat":"state","gpRef":"eq. 6.22–6.24",
 "one":"四個 32-byte 的隨機值：η_0 每塊更新，η_1..3 是前三個 epoch 結束時的快照。",
 "body":"η′_0 = H(η_0 ⌢ Y(H_V))——用 prior η_0 與 header VRF 的**輸出**。epoch 換屆時 (η′_1, η′_2, η′_3) = (η_0, η_1, η_2)。用途分工：提交 ticket 與 fallback、guarantor 分派用 η′_2；驗 seal 用 η′_3（就是晚一個 epoch 的同一個值）；`fetch` 給 accumulate 的是 η′_0。",
 "rel":["H_V","seal","guarantor assignment"]},
{"sym":"ι κ λ","term":"validator key sets","zh":"驗證者金鑰集合","cat":"state","gpRef":"eq. 6.7, 6.14",
 "one":"ι 待命（staging）、κ 現行（active）、λ 上一個 epoch。",
 "body":"epoch 換屆時 (γ′_P, κ′, λ′) = (Φ(ι), γ_P, κ)——所以 ι 要經過兩個 epoch 邊界才會成為 active（ι → γ_P → κ）。Φ 把 ψ′_O（posterior offenders）裡的 key 換成全零。ι 由具 delegator 權限的 service 透過 `designate` 設定。每個 key 是 336 octets：Bandersnatch 32 | Ed25519 32 | BLS 144 | metadata 128。",
 "rel":["γ_P","Φ","designate","ψ_O"]},
{"sym":"ρ","term":"availability assignments","zh":"可用性指派","cat":"state","gpRef":"eq. 11.1",
 "one":"每個 core 目前掛著、等待 availability 的 guarantee 與它進鏈的 slot。",
 "body":"ρ ∈ [(g ∈ 𝔾, t ∈ N_T)?]_C。0.8.0 起存的是**整個 guarantee**（含 2–3 個 guarantor 簽章），理由是要能直接向 guarantor 抓 bundle，以及在 dispute 時用這些簽章組出 culprits。中間狀態：ρ†（disputes 清掉 bad/wonky）→ ρ‡（assurances 讓它 available 或 timeout）→ ρ′（新 guarantee 進來，timestamp 記 τ′）。",
 "rel":["ρ†","ρ‡","guarantee","U"]},
{"sym":"τ","term":"timeslot","zh":"時槽","cat":"state","gpRef":"eq. 6.1",
 "one":"最近一個區塊的 slot index；τ′ = H_T。",
 "body":"存 τ 是為了能算出 epoch index 與 slot phase：e ⌢ m = τ / E，e′ ⌢ m′ = τ′ / E。很多規則都取決於「prior 的 m」還是「posterior 的 m′」——例如 γ_S 的第一種情況要求 m ≥ Y（prior），ticket extrinsic 的上限則看 m′ < Y。τ ≥ τ′ 直接是無效區塊。",
 "rel":["epoch","H_T","Y"]},
{"sym":"φ","term":"authorizer queue","zh":"授權佇列","cat":"state","gpRef":"eq. 8.1",
 "one":"每個 core 固定 Q = 80 筆的 authorizer 佇列，每個 slot 補一筆進 pool。",
 "body":"φ ∈ [[H]_Q]_C。只有該 core 的 assigner（χ_A[c]）能在 accumulate 裡用 `assign` 改它。補進 pool 的是 φ′[c][H_T mod Q]——注意用的是 **posterior** φ′，所以 pool 更新排在 accumulation 之後。（別跟 PVM 的暫存器 φ 搞混，那是另一個同形符號。）",
 "rel":["α","assign","χ_A"]},
{"sym":"χ","term":"privileges","zh":"特權服務","cat":"state","gpRef":"eq. 9.9–9.10",
 "one":"五種特權：manager、delegator、registrar、每個 core 的 assigner、always-accumulate 集合。",
 "body":"χ ≡ (χ_M, χ_V, χ_R, χ_A, χ_Z)。χ_M 可改整個 χ 並發放 gratis storage（0.8.0 起 `bless` 只有 manager 能呼叫）；χ_V 可設 ι；χ_R 可建立 index < S = 2^16 的保留 service；χ_A[c] 可改 φ[c]；χ_Z 是每塊都會被 accumulate 的 service 與其免費 gas。",
 "rel":["bless","assign","designate","χ_Z"]},
{"sym":"ψ","term":"disputes state","zh":"爭議狀態","cat":"state","gpRef":"eq. 10.1",
 "one":"good / bad / wonky 三個 report hash 集合，加上 offenders 的 Ed25519 key 集合。",
 "body":"ψ ≡ (ψ_G, ψ_B, ψ_W, ψ_O)。已經判過的 report hash 不能再被判一次（verdict 的 hash 必須與三個集合不相交）。ψ_O 只增不減，且在下次 key rotation 時讓 Φ 把對應的 validator key 清零；JAM 自己不做 slashing，只留紀錄給上層 staking 系統。",
 "rel":["verdict","culprit","fault","Φ"]},
{"sym":"π","term":"activity statistics","zh":"活動統計","cat":"state","gpRef":"eq. 13.1",
 "one":"π_V 本 epoch、π_L 上一個 epoch 的 validator 統計，加上 per-core 與 per-service 的本塊統計。",
 "body":"π ≡ (π_V, π_L, π_C, π_S)。validator 每人六個計數器：b 出塊、t 帶進的 ticket 數、p preimage 數、d preimage bytes（這四個都記在**作者**身上）、g guarantee（記在有簽名的 guarantor）、a assurance（記在簽 assurance 的人）。π_C/π_S 是 per-block 的，沒活動就不出現。JAM 只產生數據，獎勵計算交給上層。",
 "rel":["G (reporters)","π_C","π_S"]},
{"sym":"ω","term":"ready queue","zh":"待累積佇列","cat":"state","gpRef":"eq. 12.3",
 "one":"已 available 但依賴未滿足、等著被 accumulate 的 report（長度 E 的環狀緩衝）。",
 "body":"ω ∈ [[(ℝ, {H})]]_E，每格存 (report, 尚未滿足的 package hash 集合)。每塊從 ω[m..] ⌢ ω[..m] 依序取（m = H_T mod E，即最舊優先），能解鎖的用 Q 函數挑出來，跳過的 slot 清空，超過一個 epoch 沒解開就被覆蓋掉。0.7.x 的文獻寫成 ϑ，0.8.0 已改名為 ω。",
 "rel":["ξ","R!","R*","Q 函數"]},
{"sym":"ξ","term":"accumulation history","zh":"累積歷史","cat":"state","gpRef":"eq. 12.1",
 "one":"最近一個 epoch 內已被 accumulate 的 work-package hash（每個 slot 一組集合）。",
 "body":"ξ ∈ [{H}]_E。兩個用途：判斷 report 的 prerequisite 是否已滿足（依賴的 package 在 ξ 裡就算解鎖），以及擋掉重複的 package。每塊左移一格，最後一格放本塊剛 accumulate 的 package hash。",
 "rel":["ω","prerequisite","R*"]},
{"sym":"θ","term":"accumulation output log","zh":"累積輸出紀錄","cat":"state","gpRef":"eq. 7.4, 12.24",
 "one":"本塊各 service 透過 `yield` 產出的 (service, hash) 序列。",
 "body":"θ′ 由 Δ+ 的輸出 b 而來，只收「有 yield 32-byte hash」的 service。它會被 M_B（Keccak）算出一個 root，append 進 β_B 這條 MMR，其 super-peak 就是 BEEFY 簽的東西——也就是 service 對外部系統（bridge）承諾狀態的管道。",
 "rel":["yield","β_B","BEEFY"]},
{"sym":"B","term":"block","zh":"區塊","cat":"block","gpRef":"eq. 4.2",
 "one":"B ≡ (H, E)：一個 header 加一份 extrinsic。",
 "body":"JAM 是 transactionless 的：extrinsic 的五個部分全部由 validator 產生，沒有使用者簽名的交易。外部資料只能經由 work-package（in-core 的 refine）與 preimage 進入狀態。",
 "rel":["H (header)","E (extrinsic)"]},
{"sym":"E","term":"extrinsic","zh":"區塊外部資料","cat":"block","gpRef":"eq. 4.3",
 "one":"E ≡ (E_T, E_D, E_P, E_A, E_G)：tickets、disputes、preimages、assurances、guarantees。",
 "body":"E_T 出塊抽籤的票（m′ < Y 時最多 K = 16 張）；E_D 爭議（verdicts + culprits + faults，各最多 16）；E_P preimage（依 (service, blob) 排序且唯一）；E_A availability assurance（每個 validator 至多一筆，依 index 遞增）；E_G work-report guarantee（每個 core 至多一筆，依 core 排序）。",
 "rel":["E_T","E_G","E_A","E_D","E_P"]},
{"sym":"H","term":"header","zh":"區塊標頭","cat":"block","gpRef":"eq. 5.1",
 "one":"十個欄位：H_P, H_R, H_X, H_T, H_E, H_W, H_O, H_I, H_V, H_S。",
 "body":"parent hash、**prior** state root、extrinsic hash、timeslot、epoch marker、winning-tickets marker、offenders marker、作者 index、entropy VRF 簽章、seal。E_U(H) 是「不含 seal」的序列化，也就是 seal 簽的訊息。",
 "rel":["H_R","H_S","H_V","E_U(H)"]},
{"sym":"H_R","term":"prior state root","zh":"前態狀態根","cat":"block","gpRef":"§5",
 "one":"header 帶的是**父區塊**的 posterior state root，不是自己的。",
 "body":"GP 明說理由是「to facilitate the pipelining of block computation and in particular of Merklization」——出塊者不必先把新狀態 Merklize 完才能發布區塊。代價是 β 最新一筆的 state root 要留白、由下一塊補（β†），以及 Grandpa 投票必須另外帶上 posterior state root。",
 "rel":["β†","Grandpa","pipelining"]},
{"sym":"H_S / H_V","term":"seal / entropy VRF signature","zh":"封印與熵簽章","cat":"block","gpRef":"eq. 6.16–6.18",
 "one":"兩個 Bandersnatch VRF 簽章：一個證明出塊權，一個產生熵。",
 "body":"ticket 模式：Y(H_S) 必須等於該 slot 的 ticket id，context 是 X_T ⌢ η′_3 ++ i_e，訊息是 E_U(H)，並標記 T = 1。fallback 模式：γ_S[H_T mod E] 必須等於作者的 Bandersnatch key，context 改 X_F ⌢ η′_3，T = 0。兩種模式都要有 H_V：context X_E ⌢ Y(H_S)、訊息為空——訊息先被固定住，所以熵無法被出塊者操弄。",
 "rel":["γ_S","η","T (ticketed)","Bandersnatch"]},
{"sym":"H_X","term":"extrinsic hash","zh":"外部資料雜湊","cat":"block","gpRef":"eq. 5.4–5.7",
 "one":"對五個 extrinsic 元件各自的承諾再取一次 hash。",
 "body":"0.8.0 (#524) 改成：preimage 部分承諾 (E_4(service), H(data)) 對，guarantee 部分承諾 (H(report), E_4(slot), credential)。目的是「allow for the possibility of reports and preimages to individually have their inclusion proven」——不必附上整個 blob 就能證明某筆在區塊裡。",
 "rel":["E_P","E_G","Merkle proof"]},
{"sym":"H_E / H_W / H_O","term":"epoch / winning-tickets / offenders markers","zh":"三個標記","cat":"block","gpRef":"eq. 6.28–6.29, 10.19",
 "one":"讓只同步 header 的節點也能追上 validator 與 ticket 的變化。",
 "body":"H_E 只在 e′ > e 時出現，內容是 (η_0, η_1) 加上 γ′_P 每個 validator 的 (Bandersnatch, Ed25519) key。H_W 只在同一 epoch 內首次跨過 Y、且 accumulator 飽和時出現，內容是 Z(γ_A)。H_O 是本塊新增的 offender key（culprits 在前、faults 在後），可以是空序列。H_E 與 H_W 互斥。",
 "rel":["γ_P","γ_A","Z","offenders"]},
]
