# -*- coding: utf-8 -*-
# Glossary — actors, the in-core pipeline, and its data structures
TERMS = [
{"sym":"","term":"in-core vs on-chain","zh":"核內／鏈上","cat":"flow","gpRef":"§4.9.1",
 "one":"in-core 只有被指派的少數 validator 執行；on-chain 是所有人都跑。",
 "body":"in-core（refine）由該 core 的 guarantor 執行，靠 guaranteeing → assuring → auditing →（必要時）judging 這套 crypto-economic 遊戲取信，因此算力可隨網路規模成長（GP 估計約單機的 300 倍）；on-chain（accumulate）是「everybody does everything」，受單機能力限制。兩者由同一批 validator 執行，安全性相當，差別在「可擴展 vs 同步」。",
 "rel":["refine","accumulate","ELVES"]},
{"sym":"","term":"refine","zh":"精煉","cat":"flow","gpRef":"§4.9.2, eq. B.5",
 "one":"service 的 in-core 進入點：無狀態、吃大量輸入、吐出小的 digest。",
 "body":"Ψ_R 在 core 上執行，沒有一般的鏈上狀態可讀（只有 historical_lookup 能依 lookup-anchor 時點查 preimage），但可以建立 inner PVM、export segment 到 D³L。每個 work-item 一次 refine，gas 上限 G_R = 5×10^9。輸出（work result）與統計資料組成 work-digest。",
 "rel":["accumulate","work-item","Ψ_R","historical_lookup"]},
{"sym":"","term":"accumulate","zh":"累積","cat":"flow","gpRef":"§12, eq. B.9",
 "one":"service 的 on-chain 進入點：有狀態、可轉帳、可建立 service。",
 "body":"Ψ_A 以 PC = 5 為進入點，參數只有 (timeslot, service id, input 數)，實際的 operand 與 transfer 用 `fetch`(14/15) 讀。每個 report 的 accumulate gas 上限 G_A = 10^7、每塊總量 G_T = 3.5×10^9。0.7.1 起 on_transfer 併入 accumulate——轉帳以 input 的形式在下一輪送達收款方。",
 "rel":["refine","Δ+","deferred transfer","yield"]},
{"sym":"","term":"guarantor","zh":"保證人","cat":"flow","gpRef":"§11.3, §15",
 "one":"被指派到某個 core、負責執行 refine 並簽署 work-report 的 validator。",
 "body":"每個 active core 固定 3 個 guarantor，由 η′_2 對 [⌊i/3⌋] 做 Fisher–Yates shuffle、再依 rotation index ⌊(t mod E)/R⌋ 旋轉決定（R = 10 slots 換一次）。兩個簽章就足以把 report 送給出塊者。GP 建議「平均每個 slot 簽不超過兩份 report」，以免被出塊者當成 spam 忽略。",
 "rel":["M (assignments)","rotation","guarantee","R (常數)"]},
{"sym":"","term":"assurer","zh":"擔保人","cat":"flow","gpRef":"§11.2, §16",
 "one":"宣告自己已持有某 core 的 erasure-coded shard 的 validator。",
 "body":"每個 slot 發一份 assurance：bitfield 每個 core 一 bit，anchor 必須是 H_P，用 prior κ 的 Ed25519 key 對 X_A ⌢ H(E(H_P, bitfield)) 簽名。要打勾必須同時握有兩類 shard：report bundle 的（審計用，審完可丟）與所有 exported segment 的（保存 28 天）。超過 2/3·|κ| 打勾，report 才算 available。",
 "rel":["assurance","erasure coding","D³L","R (available)"]},
{"sym":"","term":"auditor","zh":"審計者","cat":"flow","gpRef":"§17",
 "one":"每個 validator 都要對隨機抽到的 report 重跑一次並公開判決。",
 "body":"初始 tranche：用 X_U ⌢ Y(H_V) 的 VRF 洗牌後取 10 個 core。之後每 8 秒（A）一個 tranche，遇到負面判決或 no-show（有人宣告卻沒交判決）就擴大，期望每個 no-show 多帶 F = 2 個審計者。審計要先把 bundle 從 1/3 的 validator 手上的 chunk 重建出來，再重跑 computereport 逐欄位比對。",
 "rel":["ELVES","no-show","tranche","A","F"]},
{"sym":"","term":"ELVES","zh":"ELVES 機制","cat":"flow","gpRef":"§17 & eprint 2024/961",
 "one":"JAM 審計機制的理論基礎，源自 Polkadot 的 backing/approval/inclusion。",
 "body":"論文用語與 JAM 的對照：backing = guaranteeing、approval = auditing、inclusion = accumulation。核心想法是「非冗餘分割 + 提案與審計賽局」——不需要所有人重算，只要作弊被抓到的機率夠高、代價夠大即可。安全性假設 ≥ 2/3+1 的 validator 誠實且在線。",
 "rel":["auditor","guarantor","dispute"]},
{"sym":"P","term":"work-package","zh":"工作包","cat":"data","gpRef":"eq. 14.2",
 "one":"⟨j, h, u, f, c, w⟩：授權 token、授權服務、授權 code hash、config、refinement context、work-items。",
 "body":"authorizer = H(u ⌢ f)。一個 package 最多 I = 16 個 work-item，整包（含 extrinsic 與 import）不得超過 W_B = 13,791,360 octets。package 由 builder 組裝、交給 guarantor；它本身不上鏈，上鏈的是它的 work-report。",
 "rel":["work-item","authorizer","work-report","W_B"]},
{"sym":"","term":"work-item","zh":"工作項","cat":"data","gpRef":"eq. 14.3",
 "one":"package 內的一個工作單位：指定 service、code hash、payload、兩個 gas 上限、imports、extrinsics、export 數。",
 "body":"每個 item 對應一次 refine 與（之後）一筆 work-digest。imports 以 (segment root 或 package hash, index) 指定要從 D³L 匯入的 segment；extrinsics 以 (hash, length) 指定隨包附帶的資料。宣告的 export 數若與實際 export 不符，結果會被換成 BADEXPORTS。",
 "rel":["work-package","work-digest","segment","refine"]},
{"sym":"ℝ","term":"work-report","zh":"工作報告","cat":"data","gpRef":"eq. 11.2",
 "one":"(s, c, c, a, t, l, d, g)：avspec、refinement context、core、authorizer、auth trace、segment-root lookup、digests、auth gas。",
 "body":"這是 in-core 計算「上鏈」的形式：不含原始資料，只含承諾與結果。變動大小（auth trace + 所有成功輸出）受 W_R = 48 KiB 限制；digest 數 1..16；|segment-root lookup| + |prerequisites| ≤ J = 8。report 的 hash H(E(w)) 是 dispute 與 ρ 清除時的識別碼。",
 "rel":["work-digest","avspec","refinement context","W_R"]},
{"sym":"𝔻","term":"work-digest","zh":"工作摘要","cat":"data","gpRef":"eq. 11.6",
 "one":"一個 work-item 的 refine 結果加上資源使用量。",
 "body":"欄位：service、code hash（必須與鏈上 δ[s]_c 相符）、payload hash、accumulate gas 上限、結果（blob 或錯誤）、實際用掉的 refine gas、import 數、extrinsic 數與大小、export 數。accumulate 時它會被轉成 operand tuple 餵給 service。",
 "rel":["work-report","operand tuple","𝔼"]},
{"sym":"𝔼","term":"work error set","zh":"工作錯誤集合","cat":"data","gpRef":"eq. 11.7",
 "one":"{∞ OOG, ☇ panic, BADEXPORTS, OVERSIZE, BAD, BIG}。",
 "body":"∞ gas 用盡、☇ 非預期終止、BADEXPORTS 宣告的 export 數不符、OVERSIZE 輸出會撐破 report 的大小上限、BAD 在 lookup-anchor 的狀態下找不到 service code、BIG code 超過 W_C = 4,000,000。錯誤仍然會被 accumulate（operand 的結果就是錯誤值），只是沒有輸出 blob。注意 0.8.0 的 𝕁 是 segment 的集合，不是錯誤集合。",
 "rel":["work-digest","𝕁","W_C"]},
{"sym":"𝕐","term":"availability specification","zh":"可用性規格","cat":"data","gpRef":"eq. 11.5",
 "one":"(p, l, u, v, e, n)：package hash、bundle 長度、erasure root、shard 數、segment root、segment 數。",
 "body":"u 是對所有 erasure chunk 的 Merkle root（審計與重建的依據）；v 必須等於 |κ′|，因為每個 assurer 拿一個 chunk；e 是對 exported segment 做的 constant-depth Merkle root，供之後的 package import 時驗證。容易記反的是 v（shards）與 n（segments）。",
 "rel":["erasure coding","segment","assurer"]},
{"sym":"ℂ","term":"refinement context","zh":"精煉語境","cat":"data","gpRef":"eq. 11.4",
 "one":"(a, n, s, b, l, t, r, p)：anchor 四件組、lookup-anchor 三件組、prerequisites。",
 "body":"anchor（hash、slot、posterior state root、accumulation-output super-peak）必須對上 β† 的某一筆，也就是最多 8 塊以內；lookup-anchor（hash、slot、posterior state root）必須在最近 L = 14,400 slots 的 ancestor 裡找得到——這是少數無法只靠鏈上狀態驗證、必須保留 header 鏈的檢查。prerequisites 是本 report 依賴的 package hash。",
 "rel":["anchor","lookup anchor","β†","ancestors"]},
{"sym":"","term":"authorizer / token / trace","zh":"授權者／憑證／軌跡","cat":"data","gpRef":"§8.1",
 "one":"authorizer 是判斷「這個 package 能不能用這個 core」的邏輯；token 是隨包附上的憑證；trace 是授權成功的輸出。",
 "body":"authorizer 的身分是 H(auth code hash ⌢ config)。它在 in-core 執行（Ψ_I，gas 上限 G_I = 5×10^7），鏈上只檢查 authorizer hash 有沒有在該 core 的 pool 裡。這個設計把「誰買了 coretime」與「誰提交工作」拆開，因此同時支援 Ethereum 式與 Polkadot 式的使用模式。",
 "rel":["α","coretime","Ψ_I"]},
{"sym":"𝕁","term":"segment","zh":"分段","cat":"data","gpRef":"eq. 14.1, §14.4",
 "one":"D³L 的固定大小資料單位，W_G = 4,104 octets。",
 "body":"refine 用 `export` 產生 segment、用 import 取回別的 package 之前 export 的 segment。每個 package 最多 3,072 個 import 與 3,072 個 export。segment 在 Audit DA 的額外足跡是 W_F = W_G + 32·⌈log₂ W_X⌉ = 4,488（多出來的是 justification 路徑）。segment 保存 28 天。",
 "rel":["D³L","export","W_G","W_F"]},
{"sym":"","term":"D³L / DA","zh":"資料可用性層","cat":"data","gpRef":"§16, §17.2",
 "one":"兩套資料可用性：audit DA（bundle，短期）與 import DA（segment，28 天）。",
 "body":"audit DA 讓審計者能重建 work-package bundle 重跑計算，審計完成即可丟棄；import DA（也就是 D³L，Distributed Data Lake）保存 exported segment 28 天，讓後續的 work-package 能 import 前人算出的資料，而不必重新塞進可用性系統——這是 JAM 相對於單純 rollup DA 的特色。",
 "rel":["segment","assurer","erasure coding"]},
{"sym":"𝔾","term":"guarantee","zh":"保證","cat":"data","gpRef":"eq. 11.24–11.28",
 "one":"(work-report, slot, 2–3 個 (validator index, Ed25519 簽章))。",
 "body":"簽的是 X_G ⌢ H(E(report))。簽署者必須在該 slot 被指派到該 core：t 落在本 rotation 就用 M，落在前一個 rotation 就用 M*；視窗是 R·(⌊τ′/R⌋ − 1) ≤ t ≤ τ′。core 必須是 active（index < |κ′|/3），即使前一個 rotation 時它是 active 也一樣。credential 依 validator index 排序且唯一。",
 "rel":["guarantor","M","rotation","reporters"]},
{"sym":"","term":"assurance","zh":"可用性擔保","cat":"data","gpRef":"eq. 11.11–11.16",
 "one":"(anchor, bitfield, validator index, Ed25519 簽章)。",
 "body":"anchor 必須等於 H_P；bitfield 長度 C bits（full 是 43 bytes，LSB-first 打包）；只能對 ρ†[c] ≠ ∅ 的 core 打勾；整份 extrinsic 依 validator index 嚴格遞增。計票是**逐塊**的：狀態裡沒有跨塊累計器，所以必須某一塊單獨湊到 > 2/3·|κ|。",
 "rel":["assurer","R (available)","ρ‡"]},
{"sym":"","term":"verdict / culprit / fault","zh":"判決／共犯／過失","cat":"data","gpRef":"eq. 10.2–10.13",
 "one":"verdict 是一組判決票；culprit 是保證過壞 report 的人；fault 是投了與 verdict 相反票的人。",
 "body":"每個 verdict 恰好帶 ⌊2|k|/3⌋+1 張票（tiny 5、full 683），正票數只能是這個數（good）、0（bad）或 ⌊|k|/3⌋（wonky），其餘任何組合都讓區塊無效。verdict 的 epoch index 決定用 κ 還是 λ 驗簽。0.8.0 加了每份 extrinsic 最多 16 verdicts / 16 culprits / 16 faults，並取消了「bad verdict 必須附 ≥ 2 個 culprit」。",
 "rel":["ψ","ρ†","offenders"]},
{"sym":"𝕏","term":"deferred transfer","zh":"延遲轉帳","cat":"data","gpRef":"eq. 12.14",
 "one":"(sender, dest, amount, 128-byte memo, gas)。",
 "body":"`transfer` 呼叫當下就從發送方扣款（並檢查扣完仍高於自身 threshold，否則 CASH），但接收方要到 Δ+ 的**下一輪**才會以 input 形式收到並入帳。gas 欄位是預付給接收方處理這筆轉帳的量，必須 ≥ 接收方的 a_m（否則 LOW）。轉給已被刪除的 service 會被丟棄。",
 "rel":["accumulate","transfer","Δ+"]},
{"sym":"𝕌","term":"operand tuple","zh":"運算元組","cat":"data","gpRef":"eq. 12.13",
 "one":"accumulate 看到的每個 work-digest：(package hash, segment root, authorizer, payload hash, gas limit, auth trace, result)。",
 "body":"accumulate 不會拿到整個 work-report，而是這種抽出重點的元組；它們與收到的 deferred transfer 一起，透過 `fetch`(14/15) 讀入。同一個 service 在同一輪的所有 digest 會合併成一次 PVM 呼叫，以攤銷啟動成本。",
 "rel":["accumulate","work-digest","fetch"]},
{"sym":"R","term":"newly available reports","zh":"新可用報告","cat":"flow","gpRef":"eq. 11.17",
 "one":"本區塊因 assurance 達標而變成 available 的 report 序列。",
 "body":"R ≡ [ρ†[c] 的 report | Σ_a a_f[c] > 2/3·|κ|]。它接著被拆成 R!（沒有依賴、立刻累積）與 R^Q（有依賴、進 ω 排隊），合起來經 Q 函數得到本塊真正要 accumulate 的序列 R*。0.7.x 文獻寫作 W。注意別跟常數 R（rotation period = 10）或 rotation 函數 R(c, n) 搞混。",
 "rel":["ω","ξ","R*","assurance"]},
{"sym":"G","term":"reporters","zh":"報告者集合","cat":"flow","gpRef":"eq. 11.28",
 "one":"本塊 guarantee credential 裡出現過簽章的 validator 的 Ed25519 key 集合。",
 "body":"唯一用途是統計：π 的 g 計數器對每個 κ′[v] ∈ G 的 validator +1。0.7.x 文獻把它寫成 R，容易與「新可用報告 R」混淆——0.8.0 改成 G。",
 "rel":["π","guarantee","R (available)"]},
]
