# -*- coding: utf-8 -*-
# Glossary — PVM, host calls, cryptography, codec & Merklization
TERMS = [
{"sym":"PVM","term":"Polkadot Virtual Machine","zh":"Polkadot 虛擬機","cat":"pvm","gpRef":"§4.7, 附錄 A",
 "one":"以 RISC-V RV64EM 為基礎的暫存器機：13 個 64-bit 暫存器、4 KiB 分頁、32-bit 定址。",
 "body":"選 RISC-V 的理由：可高效重編譯到 x86-64/ARM、有 LLVM 工具鏈、指令語意確定（沒有浮點等非決定性行為）、易於計量，且能自然支援暫停／續跑（CorePlay 需要）。相較 EVM 少了密碼學指令與環境互動指令——那些都走 host call。",
 "rel":["φ","host call","Ψ","gas"]},
{"sym":"φ","term":"registers","zh":"暫存器","cat":"pvm","gpRef":"eq. A.47",
 "one":"13 個 64-bit 暫存器 φ_0..φ_12。",
 "body":"標準初始化：φ_0 = 2^32 − 2^16（return address；dynamic jump 到這裡就是 halt）、φ_1 = stack pointer、φ_7 = 參數位址、φ_8 = 參數長度，其餘為 0。host call 也用 φ_7 起算的暫存器傳參數與回傳值。（0.7.x 的文獻用 ω 表示暫存器，0.8.0 已改為 φ——ω 現在是 ready queue。）",
 "rel":["PVM","host call","standard init"]},
{"sym":"ϱ","term":"gas counter","zh":"gas 計數器","cat":"pvm","gpRef":"§A.5, eq. A.54",
 "one":"以 basic block 為單位、事先扣除的計量單位。",
 "body":"0.8.0 起：進入一個 basic block（或跳回它的開頭）時，先把整個 block 的成本扣掉；不夠就以 ∞（out-of-gas）中止且**不扣款**。成本 ϱ^Δ = max(cycles − 3, 1)，cycles 來自一個模擬的亂序 CPU（32 條目 reorder buffer、每 cycle 4 decode / 5 start、ALU/LOAD/STORE/MUL/DIV 單元，記憶體延遲 𝔪 = 25）。0.7.x 是「每條指令 1 gas」。",
 "rel":["basic block","∞","gas model"]},
{"sym":"μ","term":"memory","zh":"記憶體","cat":"pvm","gpRef":"eq. 4.24, A.9–A.10",
 "one":"2^32 個 octet，分成 Z_P = 4,096 octet 的頁，每頁可為 R、W 或不可存取。",
 "body":"低於 2^16 的位址一律直接 panic（null pointer 保護），其他不可存取的位址則產生 page fault，回報**最低**那個不可存取的頁位址（可以補頁後續跑）。標準初始化把 RO data 放在 Z_Z = 2^16、RW/heap 在 2Z_Z + Z(|o|)、stack 與參數放在高位址，每段之間留一個 64 KiB 的 guard zone。",
 "rel":["Z_P","Z_Z","page fault","standard init"]},
{"sym":"ε","term":"exit reason","zh":"結束原因","cat":"pvm","gpRef":"eq. A.1",
 "one":"∎ halt、☇ panic、∞ out-of-gas、page fault × 位址、host call × id。",
 "body":"halt 與 panic 是最終狀態（回傳的 instruction counter 為 0）；其餘三種都可以「續跑」：補記憶體、補 gas、或執行 host call 後把 PC 前進 1 + skip。這個設計讓 refine 能建立 inner PVM 並代理它的 host call（CorePlay 的 pause/resume 也是靠它）。",
 "rel":["PVM","host call","page fault"]},
{"sym":"ϖ","term":"basic blocks","zh":"基本區塊","cat":"pvm","gpRef":"§A.3",
 "one":"以 terminator 指令切分的程式片段，是 gas 計費與跳躍目標的單位。",
 "body":"terminator 包含 trap、fallthrough、jump、jump_ind、load_imm_jump(_ind) 與所有 branch_*。任何靜態跳躍、動態跳躍與 branch 的目標（包含 branch 不成立時的下一條）都必須是 basic block 的開頭，否則 panic。0.8.0 的 deblob 還要求程式最後一個 block 必須以 terminator 收尾。",
 "rel":["ϱ","djump","deblob"]},
{"sym":"Ψ","term":"PVM invocation functions","zh":"PVM 呼叫函數","cat":"pvm","gpRef":"eq. A.1, A.38, B.1/B.5/B.9",
 "one":"Ψ 單純執行、Ψ_H 代理 host call、Ψ_M 帶參數與回傳、Ψ_I/Ψ_R/Ψ_A 是三種協定用途。",
 "body":"Ψ_I is-authorized（無狀態，只有 gas/grow_heap/fetch）；Ψ_R refine（多了 historical_lookup、export 與 inner PVM 那一組）；Ψ_A accumulate（多了 read/write/lookup/info 與所有會改狀態的 host call）。三者都以 Ψ_M 包裝，差別在 entry point 與 host-call 分派函數。",
 "rel":["host call","refine","accumulate"]},
{"sym":"","term":"host call","zh":"宿主呼叫","cat":"pvm","gpRef":"附錄 B",
 "one":"PVM 透過 `ecalli` 呼叫外界的介面，0.8.0 編號 0–27。",
 "body":"gas 0、grow_heap 1、fetch 2、lookup 3、read 4、write 5、info 6、historical_lookup 7、export 8、machine 9、peek 10、poke 11、pages 12、invoke 13、expunge 14、bless 15、assign 16、designate 17、checkpoint 18、new 19、upgrade 20、transfer 21、eject 22、query 23、solicit 24、forget 25、yield 26、provide 27；JIP-1 另定義 log = 100。未知編號扣 M_∅ = 1000 gas 並回傳 WHAT。0.8.0 因為插入 grow_heap，整組編號比 0.7.2 位移了一格。",
 "rel":["Ψ","WHAT","gas cost"]},
{"sym":"","term":"host-call result codes","zh":"宿主呼叫回傳碼","cat":"pvm","gpRef":"§B.1",
 "one":"OK = 0；錯誤碼從 2^64−1 往下數。",
 "body":"NONE 2^64−1（項目不存在）、WHAT −2（名稱未知）、OOB −3（inner PVM 記憶體不可存取）、WHO −4（index 未知）、FULL −5（空間不足或已配置）、CORE −6、CASH −7（餘額不足）、LOW −8（gas 太低）、HUH −9（操作不合法或權限不足）。inner PVM 另有 HALT 0 / PANIC 1 / FAULT 2 / HOST 3 / OOG 4。常見混淆：WHO 是「找不到」，HUH 是「不能這樣做」。",
 "rel":["host call","WHO","HUH"]},
{"sym":"","term":"fetch","zh":"fetch 宿主呼叫","cat":"pvm","gpRef":"§B.5 (index 2)",
 "one":"三種 invocation 共用的萬用讀取介面，用 φ_10 選資料。",
 "body":"selector 0 是協定常數的編碼（JIP-4 chainspec 的 protocol_parameters 用同一格式）、1 是 η′_0、2 auth trace、3–6 extrinsic 與 import segment、7–13 package/config/token/context/item 摘要/payload、14–15 accumulate 的 inputs。共通模式是「把資料的 [offset, offset+length) 寫進記憶體、回傳資料的完整長度」，不可用時回 NONE。",
 "rel":["host call","accumulate","refine"]},
{"sym":"","term":"checkpoint / yield","zh":"checkpoint 與 yield","cat":"pvm","gpRef":"§B.7 (18, 26)",
 "one":"checkpoint 存檔（panic/OOG 時採用），yield 提交 32-byte 的 accumulation 輸出。",
 "body":"accumulate 的 context 是一對 (x, y)：x 是正常維度、y 是例外維度，只有 `checkpoint` 會把 x 複製進 y。若程式以 ☇ 或 ∞ 結束，collapse 函數採用 y——也就是最後一次 checkpoint 的狀態；正常結束才用 x。yield 寫下的 hash 會進 θ、再進 β_B 的 MMR，最後被 BEEFY 簽名。",
 "rel":["accumulate","θ","BEEFY"]},
{"sym":"H","term":"Blake2b","zh":"Blake2b 雜湊","cat":"crypto","gpRef":"§3.8",
 "one":"GP 的預設雜湊函數，輸出 32 octets。",
 "body":"state trie、extrinsic hash、report hash、entropy、state key 等絕大多數地方都用 H。例外是 accumulation-output belt 與 BEEFY 相關的 H_K（Keccak）——那是為了讓 EVM 這類「legacy systems」能便宜地驗證。",
 "rel":["H_K","state trie","BEEFY"]},
{"sym":"H_K","term":"Keccak","zh":"Keccak 雜湊","cat":"crypto","gpRef":"§7, §18",
 "one":"只用在 accumulation output 的 Merkle root、MMR 與 BEEFY 承諾。",
 "body":"GP 原文：「Throughout, the Keccak hash function is used to maximize compatibility with legacy systems」。實務意義：橋接合約可以用 EVM 便宜的 keccak256 precompile 驗證 JAM 的 accumulation output 證明。",
 "rel":["H","β_B","BEEFY"]},
{"sym":"","term":"Bandersnatch VRF","zh":"Bandersnatch VRF","cat":"crypto","gpRef":"附錄 G",
 "one":"建構在 BLS12-381 純量域上的曲線，JAM 用它做 seal、entropy 與 ring proof。",
 "body":"兩種用法：(1) 一般（IETF 式）VRF——seal H_S、entropy H_V、審計選擇 s_n 都是；(2) ring VRF——提交 ticket 時證明「我是 γ_Z 這個 ring 裡的某個人」而不揭露身分。VRF 的輸出 Y(·) 只取決於 context 與訊息，這是 ticket id 與 entropy 的來源。",
 "rel":["ticket","seal","γ_Z","ring root"]},
{"sym":"","term":"signing contexts","zh":"簽章語境字串","cat":"crypto","gpRef":"附錄 I",
 "one":"每種簽章都有專屬前綴，避免跨用途重放。",
 "body":"$jam_ticket_seal（X_T）、$jam_fallback_seal（X_F）、$jam_entropy（X_E）、$jam_available（X_A）、$jam_guarantee（X_G）、$jam_valid / $jam_invalid（判決）、$jam_audit（X_U）、$jam_announce、$jam_beefy。面試常考「這個簽章的 context 與訊息各是什麼」——例如 seal 的訊息是 E_U(H)，而 H_V 的訊息是空序列。",
 "rel":["seal","assurance","guarantee","BEEFY"]},
{"sym":"E","term":"codec","zh":"編碼函數","cat":"codec","gpRef":"附錄 C",
 "one":"JAM 自己的序列化：緊湊自然數 + 固定寬度整數 + 長度前綴序列。",
 "body":"E(0) = [0]；小於 128 的數是單一 byte；再大就用「前綴的高位放幾個 1 表示後面還有幾個 byte」的形式；≥ 2^56 用 0xFF + 8 bytes LE。↕x 表示需要長度前綴的變長項；x? 是 0 或 1 ⌢ x；dictionary 依 key 排序；bit sequence 以 LSB-first 打包。注意這與 SCALE 的 compact 不同（SCALE 用最低兩個 bit 當模式）。",
 "rel":["E_l","state serialization","SCALE"]},
{"sym":"E_l","term":"fixed-length encoding","zh":"固定長度編碼","cat":"codec","gpRef":"附錄 C, D",
 "one":"E_2/E_4/E_8：little-endian 的定寬整數。",
 "body":"狀態序列化裡「所有非 discriminator 的數值都用定寬」（附錄 D 的註）。區塊／extrinsic 則逐結構定義：timeslot E_4、**所有 validator index 都是 E_2**、service index E_4、gas E_8、長度前綴才用緊湊 E。",
 "rel":["E","state serialization"]},
{"sym":"C(i)","term":"state key constructor","zh":"狀態鍵建構子","cat":"codec","gpRef":"§D.1",
 "one":"把狀態元件或 service 資料對應到 31-octet 的 trie key。",
 "body":"三種形式：C(i) = [i, 0, …]（第 i 章的單一元件，1 α、2 φ、3 β、4 γ、5 ψ、6 η、7 ι、8 κ、9 λ、10 ρ、11 τ、12 χ、13 π、14 ω、15 ξ、16 θ）；C(i, s) 把 service id 的 4 個 byte 與 0 交錯（C(255, s) 是 account info）；C(s, h) 把 service id 與 H(h) 的前 4 byte 交錯、再接 hash 的第 4..26 byte。storage/preimage/request 分別用 E_4(2^32−1)、E_4(2^32−2)、E_4(length) 當前綴避免碰撞。",
 "rel":["state trie","δ","E_4"]},
{"sym":"","term":"state trie","zh":"狀態樹","cat":"codec","gpRef":"§D.2",
 "one":"binary Patricia Merkle trie，節點固定 512 bits。",
 "body":"第一個 bit 區分 branch 與 leaf。branch = 0 + 左子 hash 的後 255 bits + 右子完整 256 bits。leaf 有兩種：值 ≤ 32 octets 直接內嵌（前兩 bit 10 + 6-bit 長度 + 31-byte key + 補零的值），否則存 H(value)（前 8 bits 11000000）。空子樹是零 hash。設計目標是「optimized for modern compute hardware」——固定大小、少分支。",
 "rel":["C(i)","H","H_R"]},
{"sym":"","term":"Merkle functions","zh":"Merkle 函數群","cat":"codec","gpRef":"附錄 E",
 "one":"N 節點函數、M_B 一般根、M 定深根、MMR append 與 super-peak。",
 "body":"N 在 ⌈n/2⌉ 處切開，雜湊 $node ⌢ 左 ⌢ 右（well-balanced）。M_B 直接把原始 blob 當 leaf（刻意不逐項雜湊），用於 extrinsic hash 與每塊的 accumulation output root。M 是定深版：先把每個 leaf 雜湊成 $leaf ⌢ v、再補零 hash 到 2 的冪——segment root 與 paged proof 用它。MMR 的 append 像二進位加法進位，super-peak 用 $peak 前綴由左往右摺疊。",
 "rel":["MMR","segment root","β_B"]},
{"sym":"","term":"erasure coding","zh":"抹除碼","cat":"crypto","gpRef":"附錄 H",
 "one":"GF(2^16) 上的 systematic Reed–Solomon，任意 d(v) 個 chunk 即可還原。",
 "body":"d(v) = max{d ≤ v/3 + 1 : W_G mod 2d = 0}；v = 1023 → 342、v = 6 → 3。也就是「即使將近三分之二的 validator 惡意或離線也能重建」。systematic 的好處是前 d 個 chunk 就是原始資料，直接串接即可。每個 validator 每個 segment 拿到的是 12 octets（full 配置）。",
 "rel":["assurer","D³L","avspec"]},
{"sym":"","term":"Fisher–Yates shuffle","zh":"洗牌函數","cat":"crypto","gpRef":"附錄 F",
 "one":"以 32-byte 熵驅動的確定性洗牌，用於 guarantor 分派與審計選擇。",
 "body":"用 Q_l(h)[i] = decode_4(H(h ⌢ E_4(⌊i/8⌋))[4(i mod 8) …]) 產生亂數序列——一次雜湊供應 8 個 32-bit 數。取 r[i] mod 剩餘長度、輸出該元素、再把最後一個元素搬進空位。確定性是關鍵：所有節點必須算出同一個分派。",
 "rel":["guarantor","M (assignments)","auditor"]},
]
