# -*- coding: utf-8 -*-
# Glossary — constants, off-chain protocol, ecosystem
TERMS = [
{"sym":"C = 341","term":"core count","zh":"核心數","cat":"const","gpRef":"附錄 I",
 "one":"總 core 數固定 341，但只有前 |κ′|/3 個是 active。",
 "body":"每個 active core 需要 3 個 guarantor，所以 full 配置 |κ| = 1023 = 3·341 時全部 341 個 core 都 active。0.8.0 允許較小的 validator 集合（6 到 1023 的 3 的倍數），此時 active core 數等比例縮小，超出範圍的 core 永遠是 ∅。",
 "rel":["𝕍","guarantor","active core"]},
{"sym":"E = 600 / P = 6","term":"epoch length / slot period","zh":"epoch 長度／時槽長度","cat":"const","gpRef":"§4.8",
 "one":"每個 slot 6 秒、每個 epoch 600 slots（正好一小時）。",
 "body":"timeslot index 是自 JAM Common Era（2025-01-01 12:00 UTC，Unix 1,735,732,800）起算的 6 秒週期數，型別 N_2^32（可用到西元 2840 年）。中午 UTC 的選擇是為了讓「距起點 24 小時整數倍」的時刻在所有主要時區都是同一天。",
 "rel":["τ","Y","JAM Common Era"]},
{"sym":"Y = 500","term":"epoch tail start","zh":"票券截止點","cat":"const","gpRef":"§6.7",
 "one":"epoch 的第 500 個 slot 之後不再接受 ticket。",
 "body":"m′ < Y 時每塊最多 K = 16 張 ticket，之後 E_T 必須是空的。這段「尾巴」讓下個 epoch 的 slot-sealer 序列有時間定案：只有在 prior 區塊的 m ≥ Y 且 accumulator 飽和時，下個 epoch 才會使用 ticket，否則走 fallback。",
 "rel":["γ_S","γ_A","K","fallback"]},
{"sym":"R = 10","term":"rotation period","zh":"輪替週期","cat":"const","gpRef":"§11.3",
 "one":"guarantor 與 core 的對應每 10 個 slot 換一次。",
 "body":"rotation index = ⌊(t mod E)/R⌋，每個 epoch 有 60 次輪替。guarantee 的 slot 可以落在本 rotation 或前一個 rotation（視窗 R·(⌊τ′/R⌋−1) ≤ t ≤ τ′）；若前一個 rotation 屬於前一個 epoch，驗證要改用 λ′ 與 η′_3。輪替是為了限制惡意 guarantor 能持續盯上同一個 core 的時間。",
 "rel":["M","M*","guarantee"]},
{"sym":"H = 8 / L = 14,400","term":"recent history / lookup anchorage","zh":"近期歷史長度／查找錨點上限","cat":"const","gpRef":"§7, eq. 11.37",
 "one":"anchor 最多回溯 8 個區塊；lookup anchor 最多回溯 14,400 slots（24 小時）。",
 "body":"兩者的驗證方式不同：anchor 對照鏈上的 β†（狀態內），lookup anchor 必須對照保存的 header 鏈（ancestors A）——這是少數無法只靠狀態驗證的規則，也是 conformance fuzzer 把 Ancestry 列為 M1 必要功能的原因。D = L + 4,800 = 19,200 是 preimage 可被真正刪除前的等待期。",
 "rel":["β†","ancestors","D"]},
{"sym":"U = 5","term":"assurance timeout","zh":"擔保逾時","cat":"const","gpRef":"eq. 11.18",
 "one":"report 進鏈後 5 個 slot 內沒湊到 2/3 擔保就被清掉。",
 "body":"條件是 H_T ≥ t + U，t 是 report **進鏈**的 slot（τ′），不是 guarantee 自己帶的 slot。0.8.0 另外規定 |κ| ≠ |κ′|（validator 集合大小改變）時所有 pending 一併清空——因為 shard 數與 assurer 集合都對不上了。被清掉的 report 不會被 accumulate，就這樣消失。",
 "rel":["ρ‡","assurance","R (available)"]},
{"sym":"G_A / G_R / G_T / G_I","term":"gas limits","zh":"gas 上限","cat":"const","gpRef":"附錄 I",
 "one":"每份 report 的 accumulate 10^7、每個 package 的 refine 5×10^9、每塊 accumulate 總量 3.5×10^9、is-authorized 5×10^7。",
 "body":"這組數字反映 in-core 與 on-chain 的不對稱：refine 的預算是 accumulate 的 500 倍，因為只有 3 個 validator 執行；accumulate 是所有人都跑，所以整塊只有 G_T。Δ+ 的實際預算 g = max(G_T, G_A·C + Σ χ_Z 的 gas)。",
 "rel":["refine","accumulate","Δ+"]},
{"sym":"W_G / W_B / W_R / W_C","term":"size limits","zh":"大小上限","cat":"const","gpRef":"附錄 I",
 "one":"segment 4,104；package bundle 13,791,360；report 變動內容 48 KiB；service code 4,000,000。",
 "body":"W_B = W_M·W_F + 4,096 + 64 + 64，其中 W_F = W_G + 32·⌈log₂ W_X⌉ = 4,488 是一個 import segment 在 Audit DA 的足跡。W_R 限制的是 auth trace 加上所有成功輸出的總和——這是為了「fair use of a block's extrinsic space」。W_A = 64,000 是 authorizer code 的上限。",
 "rel":["segment","work-package","work-report"]},
{"sym":"B_S / B_I / B_L","term":"deposit constants","zh":"押金常數","cat":"const","gpRef":"eq. 9.8",
 "one":"100 / 10 / 1：service 的基本、每項、每 octet 押金。",
 "body":"threshold balance a_t = max(0, B_S + B_I·a_i + B_L·a_o − a_f)。a_i = 2·|requests| + |storage|（一筆 preimage request 算兩項），a_o 每筆 request 算 81 + 宣告長度、每筆 storage 算 34 + key + value。餘額低於 a_t 時 write/solicit/transfer 會回 FULL 或 CASH——這是防止狀態膨脹的機制。",
 "rel":["a_t","service","FULL"]},
{"sym":"𝕍","term":"validator count set","zh":"合法驗證者數","cat":"const","gpRef":"eq. 6.8",
 "one":"𝕍 ≡ {3c | c ∈ N_[2, C+1]}：6 到 1023 之間 3 的倍數。",
 "body":"0.8.0 (#514) 把 V 從協定常數改成這個集合——validator 數可以變，所有門檻改成對 |κ| 取值：super-majority ⌊2|κ|/3⌋+1、每人票數 n = ⌈2E/|γ′_P|⌉、erasure shard 數 = |κ′|、active core 數 = |κ′|/3。這是 0.7.2 → 0.8.0 影響面最廣的變更之一。",
 "rel":["κ","C","super-majority"]},
{"sym":"","term":"tiny vs full","zh":"tiny 與 full 配置","cat":"const","gpRef":"w3f/jamtestvectors",
 "one":"測試向量用的縮小參數：6 個 validator、2 個 core、epoch 12 slots。",
 "body":"tiny：V 6、C 2、E 12、Y 10、R 4、D 32、每人 ticket 數 ⌈2·12/6⌉ = 4（0.7.x 是常數 3）、super-majority 5、verdict 門檻 5/0/2、Bandersnatch ring 大小 6、erasure d(6) = 3。full：V 1023、C 341、E 600、Y 500、R 10、D 19,200、ticket 2、super-majority 683、verdict 683/0/341、d(1023) = 342。其餘常數與 GP 相同。",
 "rel":["𝕍","test vectors","conformance"]},
{"sym":"","term":"Safrole","zh":"Safrole 出塊機制","cat":"offchain","gpRef":"§6",
 "one":"Sassafras 的簡化版：用 ring VRF 匿名決定每個 slot 唯一的出塊者。",
 "body":"每個 slot 恰好一個預先決定的持票人，因此幾乎不會分叉；未來 slot 的持有者身分匿名（抗針對性 DoS）；副產品是高品質的熵池。相對於 BABE 的抽籤（可能零個或多個 leader），Safrole 在前一個 epoch 就把整個序列定案。抽籤失敗時退回 fallback key 序列，best-chain 規則會偏好 ticket 出塊較多的鏈。",
 "rel":["γ_S","ticket","fallback","best chain"]},
{"sym":"","term":"Grandpa / finality","zh":"Grandpa 與最終性","cat":"offchain","gpRef":"§19",
 "one":"決定哪條鏈被最終確定；投票內容包含 posterior state root。",
 "body":"best block 必須：以最新 finalized block 為祖先、已被審計（isaudited）、未 finalized 的祖先中沒有 equivocation（同一 slot 兩個有效區塊）。符合條件者中選 ticket-sealed 祖先最多的那條。投票帶上 posterior state root，是為了彌補 header 只有 prior root——同一個 header 但不同 posterior root 的票會被視為不同區塊。",
 "rel":["best chain","H_R","BEEFY","isaudited"]},
{"sym":"","term":"BEEFY","zh":"BEEFY 橋接簽章","cat":"offchain","gpRef":"§18",
 "one":"對每個 finalized 區塊的 accumulation-output MMR super-peak 做 BLS 簽章。",
 "body":"C_v ≡ BLS_{κ′[v]_l}(X_B ⌢ last(β_H) 的 super-peak)，X_B = $jam_beefy。BLS 可聚合，因此能給外部系統（bridge）一份簡短的最終性證明。這條路徑全程用 Keccak，方便 EVM 驗證。",
 "rel":["θ","β_B","H_K"]},
{"sym":"","term":"coretime","zh":"核心時間","cat":"offchain","gpRef":"§4.9.2",
 "one":"JAM 取代 gas 購買模型的資源：預先購買、指派給 authorizer。",
 "body":"GP 明說 coretime 的購買機制不在本文範圍，預期由某個 system parachain（在 parachains service 裡）處理。它與 authorizer 搭配，把「誰付錢買了算力」與「誰提交具體工作」拆開——這也是為什麼 JAM 不需要交易簽章與 nonce。",
 "rel":["authorizer","α","service"]},
{"sym":"","term":"service","zh":"服務","cat":"offchain","gpRef":"§4.9.2, §9",
 "one":"JAM 唯一的帳戶型態：程式碼 + 餘額 + 狀態，permissionless 建立。",
 "body":"取代 Ethereum 的 contract/EOA 二分法。兩個進入點：refine（in-core）與 accumulate（on-chain）。CoreChains（把 Polkadot parachain 搬上 JAM）、CorePlay（用 PVM 的暫停／續跑做同步感的 actor 合約）都只是 service——JAM 本身沒有 parachain 概念，升級責任下放到 service 層。",
 "rel":["δ","refine","accumulate","CoreChains"]},
{"sym":"","term":"JAM Prize / M1","zh":"JAM Prize 與 M1","cat":"eco","gpRef":"jam.web3.foundation",
 "one":"W3F 的實作獎金；M1（IMPORTER）要求通過狀態轉換一致性測試並能匯入區塊。",
 "body":"規則 12：提交後可能被要求面試，用來確認「團隊成員確實是程式碼的作者」，且對 Gray Paper 與自己的實作都有明確的專業能力——「INABILITY TO PROVE THIS EXPERTISE MAY RESULT IN A REDUCED PRIZE OR FULL DISQUALIFICATION」。milestone 交付範本另外載明面試會被錄影，並須由 Fellowship 以鏈上 remark 批准。T&C 3.5 規定一致性以**評估當下最新的 Gray Paper 版本**為準——這就是 0.8.0 差異要熟的原因。",
 "rel":["conformance fuzzer","Gray Paper","M1 interview"]},
{"sym":"","term":"conformance fuzzer","zh":"一致性 fuzzer","cat":"eco","gpRef":"davxy/jam-conformance",
 "one":"透過 Unix socket 餵區塊、逐塊比對 state root 的測試工具。",
 "body":"同步的 request/response 協定，訊息用 JAM codec 編碼並加上 32-bit little-endian 長度前綴；流程是 PeerInfo 交握 → Initialize（附 ancestry）→ ImportBlock（回 StateRoot 或 Error）→ 不一致時 GetState 抓整份狀態產生報告。M1 必須支援 Ancestry 與 Forking 兩個 feature。W3F 的門檻俗稱「一百萬步」。",
 "rel":["M1","test vectors","ancestors"]},
{"sym":"","term":"JIP","zh":"JAM 改進提案","cat":"eco","gpRef":"polkadot-fellows/JIPs",
 "one":"Gray Paper 之外的實作標準：JIP-1..5+。",
 "body":"JIP-1 debug 用的 `log` host call（index 100，對共識無影響）；JIP-2 節點 RPC（JSON-RPC over WebSocket，通常 19800）；JIP-3 telemetry（JAM Tart）；JIP-4 chainspec（genesis_state 用 62 字元的十六進位 31-byte key、protocol_parameters 用 `fetch` selector 0 的編碼）；JIP-5 由 32-byte seed 推導驗證者金鑰（blake2b(\"jam_val_key_ed25519\" ⌢ seed) 等）。這些不在 GP 裡，但 M1 的工具鏈會用到。",
 "rel":["chainspec","log","conformance fuzzer"]},
{"sym":"","term":"0.7.2 → 0.8.0","zh":"版本差異","cat":"eco","gpRef":"graypaper v0.8.0 (2026-06-03)",
 "one":"面試最容易踩的雷：實作在 0.7.2，但一致性以最新版為準。",
 "body":"重點清單：validator 集合可變（|κ| 取代常數 V）；ρ 改存整個 guarantee；dispute 加上 16 筆上限並取消「bad verdict 需 ≥2 culprits」；`bless` 限 manager；authorizer = H(code hash ⌢ config) 統一；refinement context 增為 8 欄（anchor slot、lookup-anchor posterior root）；PVM 改成 basic-block gas 模型並新增 grow_heap（host call 編號整組位移）；host call 有了各自的 base + 每 KiB 成本；每人票數改成 ⌈2E/|γ′_P|⌉；extrinsic hash 承諾 preimage 的 hash；service 統計加回已處理 transfer 數；β 每筆多了 timeslot。",
 "rel":["𝕍","ρ","grow_heap","refinement context"]},
]
